// <auto-generated />
using System;
using Istanta.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Istanta.Migrations.Contesto1
{
    [DbContext(typeof(edro21_dbContext))]
    partial class edro21_dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Istanta.Models.Articoli", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codice");

                    b.Property<DateTime?>("DataInserimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_inserimento");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_modifica");

                    b.Property<string>("Descrizione1")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descrizione1");

                    b.Property<string>("Descrizione2")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descrizione2");

                    b.Property<string>("Descrizione3")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descrizione3");

                    b.Property<string>("Descrizione4")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descrizione4");

                    b.Property<string>("Ean")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("ean");

                    b.Property<string>("NotaTecnica")
                        .HasColumnType("text")
                        .HasColumnName("nota_tecnica");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(18, 3)")
                        .HasColumnName("peso");

                    b.Property<int?>("Reparto")
                        .HasColumnType("integer")
                        .HasColumnName("reparto");

                    b.Property<string>("Segmento")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("segmento");

                    b.Property<byte>("StatoRevisione")
                        .HasColumnType("smallint")
                        .HasColumnName("stato_revisione")
                        .HasComment("0 - non processato 1 - descrizione conad approvata 2 - descrizione conad bocciata 3 - obsoleto 4 - processato solo da edro");

                    b.Property<DateTime?>("UltimaRevisione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ultima_revisione");

                    b.Property<string>("Um")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("um");

                    b.HasKey("Id");

                    b.ToTable("articoli", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.ArticoliDescrizioni", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Approvata")
                        .HasColumnType("boolean")
                        .HasColumnName("approvata");

                    b.Property<string>("Area")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("area");

                    b.Property<bool>("Attiva")
                        .HasColumnType("boolean")
                        .HasColumnName("attiva");

                    b.Property<string>("Canale")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("canale");

                    b.Property<string>("CodiceGruppo")
                        .HasColumnType("text")
                        .HasColumnName("codice_gruppo");

                    b.Property<string>("Custom")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("custom");

                    b.Property<DateTime>("DataUltimaRicezione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_ultima_ricezione");

                    b.Property<string>("Descrizione1")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descrizione_1");

                    b.Property<string>("Descrizione2")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descrizione_2");

                    b.Property<string>("Descrizione3")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descrizione_3");

                    b.Property<string>("Descrizione4")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descrizione_4");

                    b.Property<string>("DescrizioneIndd")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("descrizione_indd");

                    b.Property<string>("Extra")
                        .HasColumnType("text")
                        .HasColumnName("extra");

                    b.Property<string>("FirmaTracciato")
                        .HasColumnType("text")
                        .HasColumnName("firma_tracciato");

                    b.Property<long?>("IdArticolo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_articolo");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<decimal?>("Peso")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)")
                        .HasColumnName("peso");

                    b.Property<string>("Um")
                        .HasColumnType("text")
                        .HasColumnName("um");

                    b.HasKey("Id");

                    b.HasIndex("IdArticolo");

                    b.ToTable("articoli_descrizioni", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.ArticoliFoto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("area");

                    b.Property<bool>("Attiva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasColumnName("attiva")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Canale")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("canale");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_inserimento");

                    b.Property<DateTime?>("DataModifica")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_modifica");

                    b.Property<string>("GuidId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guid_id");

                    b.Property<string>("Hash")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hash");

                    b.Property<long>("IdArticolo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_articolo");

                    b.Property<string>("NomeReale")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome_reale");

                    b.Property<string>("PathFoto")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("path_foto");

                    b.Property<bool>("Puntatore")
                        .HasColumnType("boolean")
                        .HasColumnName("puntatore");

                    b.Property<byte?>("StatoSelezione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("stato_selezione")
                        .HasDefaultValueSql("((1))")
                        .HasComment("0 - no selezionata 1 - primaria 2 - selezionata");

                    b.Property<byte?>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("IdArticolo");

                    b.ToTable("articoli_foto", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.AttivitaLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_registrazione");

                    b.Property<long>("IdAttivita")
                        .HasColumnType("bigint")
                        .HasColumnName("id_attivita");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<byte>("Tipo")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo");

                    b.HasKey("Id");

                    b.HasIndex("IdAttivita");

                    b.ToTable("AttivitaLogs", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.Attivitum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("Coda")
                        .HasColumnType("smallint")
                        .HasColumnName("coda");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)")
                        .HasColumnName("contract");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_fine");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_inizio");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_inserimento");

                    b.Property<long?>("IdParent")
                        .HasColumnType("bigint")
                        .HasColumnName("id_parent");

                    b.Property<short?>("IdUtente")
                        .HasColumnType("smallint")
                        .HasColumnName("id_utente");

                    b.Property<byte>("Priorita")
                        .HasColumnType("smallint")
                        .HasColumnName("priorita");

                    b.Property<short>("Progress")
                        .HasColumnType("smallint")
                        .HasColumnName("progress");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint")
                        .HasColumnName("stato");

                    b.Property<string>("StatoMsg")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("stato_msg");

                    b.Property<byte>("Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("tipo")
                        .HasDefaultValueSql("((1))");

                    b.Property<byte>("TipoProcesso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_processo")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("titolo");

                    b.HasKey("Id");

                    b.HasIndex("IdParent");

                    b.ToTable("Attivita", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.FotoEscluse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_inserimento");

                    b.Property<string>("Filtro")
                        .HasColumnType("text");

                    b.Property<long>("IdArticolo")
                        .HasColumnType("bigint")
                        .HasColumnName("idArticolo");

                    b.Property<string>("NomeReale")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nome_reale");

                    b.HasKey("Id");

                    b.HasIndex("IdArticolo");

                    b.ToTable("foto_escluse", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.RegistroOperazioni", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("area");

                    b.Property<int>("Autore")
                        .HasMaxLength(150)
                        .HasColumnType("integer")
                        .HasColumnName("autore");

                    b.Property<string>("Canale")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("canale");

                    b.Property<string>("CodiceAssociato")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("codice_associato");

                    b.Property<DateTime?>("DataElaborazionePropagazioni")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_elaborazione_propagazioni");

                    b.Property<DateTime?>("Data_Esecuzione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_esecuzione");

                    b.Property<DateTime>("Data_Registrazione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_registrazione");

                    b.Property<int?>("Esecutore")
                        .HasMaxLength(150)
                        .HasColumnType("integer")
                        .HasColumnName("esecutore");

                    b.Property<string>("FormData")
                        .HasColumnType("text")
                        .HasColumnName("formData");

                    b.Property<int?>("IdTracciato")
                        .HasColumnType("integer")
                        .HasColumnName("idTracciato");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint")
                        .HasColumnName("stato");

                    b.Property<byte>("TipoOperazione")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_operazione");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("idPromoLavorazione")
                        .HasColumnType("integer")
                        .HasColumnName("idPromoLavorazione");

                    b.Property<long?>("idPromoLavorazioniRecord")
                        .HasColumnType("bigint")
                        .HasColumnName("idPromoLavorazioniRecord");

                    b.HasKey("Id");

                    b.ToTable("registro_operazioni", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.RegistroPropagazioni", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short?>("AutoreElaborazione")
                        .HasColumnType("smallint")
                        .HasColumnName("autore_elaborazione");

                    b.Property<DateTime?>("DataElaborazione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_elaborazione");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_registrazione");

                    b.Property<long>("IdPromoLavorazioniRecord")
                        .HasColumnType("bigint")
                        .HasColumnName("idPromoLavorazioneRecord");

                    b.Property<long>("IdRegistro")
                        .HasColumnType("bigint")
                        .HasColumnName("idRegistro");

                    b.Property<byte>("Priorita")
                        .HasColumnType("smallint")
                        .HasColumnName("priorita");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint")
                        .HasColumnName("stato");

                    b.HasKey("Id");

                    b.HasIndex("AutoreElaborazione");

                    b.HasIndex("IdRegistro");

                    b.ToTable("registro_propagazioni", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codice")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codice");

                    b.Property<string>("Valore")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("valore");

                    b.HasKey("Id");

                    b.ToTable("settings", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.Utenti", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<string>("ADToken")
                        .HasColumnType("text")
                        .HasColumnName("ad_token");

                    b.Property<DateTime?>("ADTokenExpiration")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("scadenza_token_ad");

                    b.Property<string>("Cognome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("cognome");

                    b.Property<DateTime>("Data_Registrazione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_registrazione");

                    b.Property<DateTime?>("Data_Update")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_update");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome");

                    b.Property<string>("NomeUtente")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nomeUtente");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("password");

                    b.Property<string>("PolicyGroups")
                        .HasColumnType("text")
                        .HasColumnName("policyGroups");

                    b.Property<string>("PrivateKey")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("privateKey");

                    b.Property<byte>("Ruolo")
                        .HasColumnType("smallint")
                        .HasColumnName("ruolo");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint")
                        .HasColumnName("stato");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("utenti", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.UtentiFico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("IdUtente")
                        .HasColumnType("smallint")
                        .HasColumnName("id_utente");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("origin");

                    b.Property<byte>("TipoUtente")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_utente");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token");

                    b.Property<string>("UserData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_data");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("username");

                    b.Property<DateTime>("lastAccess")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_access");

                    b.HasKey("Id");

                    b.HasIndex("IdUtente");

                    b.ToTable("utenti_fico", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileAddestramento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titolo")
                        .HasColumnType("text");

                    b.Property<bool>("esportaSubito")
                        .HasColumnType("boolean");

                    b.Property<string>("externalCallPerExport")
                        .HasColumnType("text");

                    b.Property<string>("externalCallPerExportPoP")
                        .HasColumnType("text");

                    b.Property<string>("externalCallPerImport")
                        .HasColumnType("text");

                    b.Property<bool>("salvaSuDb")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("AddestramentoExcel");
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcelRelazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Algoritmo")
                        .HasColumnType("text");

                    b.Property<long>("IdCampo")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCampoNavigationId")
                        .HasColumnType("bigint");

                    b.Property<string>("NomeRelazione")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("TipoCompilazione")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("IdCampoNavigationId");

                    b.ToTable("AddestramentoExcelRelazioni");
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboPagine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Formato")
                        .HasColumnType("text");

                    b.Property<short>("IdMastro")
                        .HasColumnType("smallint");

                    b.Property<int>("IdTracciato")
                        .HasColumnType("integer");

                    b.Property<int>("IdTracciatoNavigationId")
                        .HasColumnType("integer");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("IdTracciatoNavigationId");

                    b.ToTable("MenaboPagine");
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboRef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodiceGruppo")
                        .HasColumnType("text");

                    b.Property<string>("Formato")
                        .HasColumnType("text");

                    b.Property<long>("IdPagina")
                        .HasColumnType("bigint");

                    b.Property<long>("IdPaginaNavigationId")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRecordNavigationId")
                        .HasColumnType("bigint");

                    b.Property<short>("Indice")
                        .HasColumnType("smallint");

                    b.Property<string>("Meccaniche")
                        .HasColumnType("text");

                    b.Property<byte>("Selezione")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("IdPaginaNavigationId");

                    b.HasIndex("IdRecordNavigationId");

                    b.ToTable("MenaboRef");
                });

            modelBuilder.Entity("Istanta.Models_2.Promo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .HasColumnType("text");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NomePromo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("ValiditaAl")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ValiditaDal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("guidID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Promo");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoImportazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("IdAddestramento")
                        .HasColumnType("integer");

                    b.Property<int>("IdAddestramentoNavigationId")
                        .HasColumnType("integer");

                    b.Property<long?>("IdAttivita")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdAttivitaNavigationId")
                        .HasColumnType("bigint");

                    b.Property<int>("IdPromo")
                        .HasColumnType("integer");

                    b.Property<int>("IdPromoNavigationId")
                        .HasColumnType("integer");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParamsRequest")
                        .HasColumnType("text");

                    b.Property<string>("TipoMateriale")
                        .HasColumnType("text");

                    b.Property<string>("guidID")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdAddestramentoNavigationId");

                    b.HasIndex("IdAttivitaNavigationId");

                    b.HasIndex("IdPromoNavigationId");

                    b.ToTable("PromoImportazioni");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuidArea")
                        .HasColumnType("text");

                    b.Property<string>("GuidCanale")
                        .HasColumnType("text");

                    b.Property<string>("GuidFormato")
                        .HasColumnType("text");

                    b.Property<string>("GuidId")
                        .HasColumnType("text");

                    b.Property<string>("GuidPromo")
                        .HasColumnType("text");

                    b.Property<string>("GuidRaccoglitore")
                        .HasColumnType("text");

                    b.Property<short>("IdAutore")
                        .HasColumnType("smallint");

                    b.Property<string>("Meta")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("PromoLavorazioni");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codice")
                        .HasColumnType("text");

                    b.Property<string>("CodiceGruppo")
                        .HasColumnType("text");

                    b.Property<short>("IdAutore")
                        .HasColumnType("smallint");

                    b.Property<int>("IdLavorazione")
                        .HasColumnType("integer");

                    b.Property<int>("IdPromoLavorazioniNavigationId")
                        .HasColumnType("integer");

                    b.Property<long>("IdPromoTracciatiRecordNavigationId")
                        .HasColumnType("bigint");

                    b.Property<long>("IdRecordTracciato")
                        .HasColumnType("bigint");

                    b.Property<byte>("Indice")
                        .HasColumnType("smallint");

                    b.Property<string>("Meta")
                        .HasColumnType("text");

                    b.Property<byte>("Pagina")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IdPromoLavorazioniNavigationId");

                    b.HasIndex("IdPromoTracciatiRecordNavigationId");

                    b.ToTable("PromoLavorazioniRecord");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecordRegister", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("IdAutore")
                        .HasColumnType("smallint");

                    b.Property<long>("IdLavorazioneRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("IdPromoLavorazioniRecordNavigationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("TipoAzione")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("IdPromoLavorazioniRecordNavigationId");

                    b.ToTable("PromoLavorazioniRecordRegister");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("Canale")
                        .HasColumnType("text");

                    b.Property<string>("Context")
                        .HasColumnType("text");

                    b.Property<int>("IdImportazione")
                        .HasColumnType("integer");

                    b.Property<int>("IdImportazioneNavigationId")
                        .HasColumnType("integer");

                    b.Property<int>("IdPromo")
                        .HasColumnType("integer");

                    b.Property<int>("IdPromoNavigationId")
                        .HasColumnType("integer");

                    b.Property<string>("Meta")
                        .HasColumnType("text");

                    b.Property<string>("OrdineLista")
                        .HasColumnType("text");

                    b.Property<string>("Sigla")
                        .HasColumnType("text");

                    b.Property<byte>("Versione")
                        .HasColumnType("smallint");

                    b.Property<string>("guidArea")
                        .HasColumnType("text");

                    b.Property<string>("guidCanale")
                        .HasColumnType("text");

                    b.Property<string>("guidPV")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdImportazioneNavigationId");

                    b.HasIndex("IdPromoNavigationId");

                    b.ToTable("PromoTracciati");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciatiRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codice")
                        .HasColumnType("text");

                    b.Property<string>("CodiceGruppo")
                        .HasColumnType("text");

                    b.Property<bool?>("DaEsportare")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DataRegistrazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Dato")
                        .HasColumnType("text");

                    b.Property<int?>("IdAddestramento")
                        .HasColumnType("integer");

                    b.Property<int>("IdAddestramentoNavigationId")
                        .HasColumnType("integer");

                    b.Property<int>("IdTracciato")
                        .HasColumnType("integer");

                    b.Property<int>("IdTracciatoNavigationId")
                        .HasColumnType("integer");

                    b.Property<int>("IndiceEsportazione")
                        .HasColumnType("integer");

                    b.Property<int>("IndiceLettura")
                        .HasColumnType("integer");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<byte>("ModalitaInserimento")
                        .HasColumnType("smallint");

                    b.Property<string>("Scatto")
                        .HasColumnType("text");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint");

                    b.Property<byte>("Versione")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("IdAddestramentoNavigationId");

                    b.HasIndex("IdTracciatoNavigationId");

                    b.ToTable("PromoTracciatiRecord");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("IdAddestramento")
                        .HasColumnType("integer");

                    b.Property<int>("IdAddestramentoNavigationId")
                        .HasColumnType("integer");

                    b.Property<short>("Indice")
                        .HasColumnType("smallint");

                    b.Property<string>("NomeColonna")
                        .HasColumnType("text");

                    b.Property<string>("NomeColonnaOriginale")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeVisualizzato")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<byte?>("Ordinamento")
                        .HasColumnType("smallint");

                    b.Property<string>("Ruolo")
                        .HasColumnType("text");

                    b.Property<byte?>("TipoDato")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("IdAddestramentoNavigationId");

                    b.ToTable("SchemaCampiExcel");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcelRelazioni", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Condizione")
                        .HasColumnType("text");

                    b.Property<long>("IdCampo")
                        .HasColumnType("bigint");

                    b.Property<long>("IdCampoNavigationId")
                        .HasColumnType("bigint");

                    b.Property<int>("IdRelazione")
                        .HasColumnType("integer");

                    b.Property<int>("IdRelazioneNavigationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IdCampoNavigationId");

                    b.HasIndex("IdRelazioneNavigationId");

                    b.ToTable("SchemaCampiExcelRelazioni");
                });

            modelBuilder.Entity("Istanta.Models.ArticoliDescrizioni", b =>
                {
                    b.HasOne("Istanta.Models.Articoli", "IdArticoloNavigation")
                        .WithMany("ArticoliDescrizionis")
                        .HasForeignKey("IdArticolo")
                        .HasConstraintName("FK_articoli_descrizioni_articoli");

                    b.Navigation("IdArticoloNavigation");
                });

            modelBuilder.Entity("Istanta.Models.ArticoliFoto", b =>
                {
                    b.HasOne("Istanta.Models.Articoli", "IdArticoloNavigation")
                        .WithMany("ArticoliFotos")
                        .HasForeignKey("IdArticolo")
                        .IsRequired()
                        .HasConstraintName("FK_articoli_foto_articoli");

                    b.Navigation("IdArticoloNavigation");
                });

            modelBuilder.Entity("Istanta.Models.AttivitaLog", b =>
                {
                    b.HasOne("Istanta.Models.Attivitum", "IdAttivitaNavigation")
                        .WithMany("AttivitaLogs")
                        .HasForeignKey("IdAttivita")
                        .IsRequired()
                        .HasConstraintName("FK_AttivitaLogs_Attivita");

                    b.Navigation("IdAttivitaNavigation");
                });

            modelBuilder.Entity("Istanta.Models.Attivitum", b =>
                {
                    b.HasOne("Istanta.Models.Attivitum", "IdParentNavigation")
                        .WithMany("SubAttivita")
                        .HasForeignKey("IdParent")
                        .HasConstraintName("FK_Attivita_Attivita");

                    b.Navigation("IdParentNavigation");
                });

            modelBuilder.Entity("Istanta.Models.FotoEscluse", b =>
                {
                    b.HasOne("Istanta.Models.Articoli", "IdArticoloNavigation")
                        .WithMany("FotoEscluses")
                        .HasForeignKey("IdArticolo")
                        .IsRequired()
                        .HasConstraintName("FK_foto_escluse_articoli");

                    b.Navigation("IdArticoloNavigation");
                });

            modelBuilder.Entity("Istanta.Models.RegistroPropagazioni", b =>
                {
                    b.HasOne("Istanta.Models.Utenti", "IdUtenteNavigation")
                        .WithMany("RegistroPopagazionis")
                        .HasForeignKey("AutoreElaborazione")
                        .HasConstraintName("FK_registro_propagazioni_utenti");

                    b.HasOne("Istanta.Models.RegistroOperazioni", "IdRegistroNavigation")
                        .WithMany("RegistroPopagazionis")
                        .HasForeignKey("IdRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_registro_propagazioni_registro_operazioni");

                    b.Navigation("IdRegistroNavigation");

                    b.Navigation("IdUtenteNavigation");
                });

            modelBuilder.Entity("Istanta.Models.UtentiFico", b =>
                {
                    b.HasOne("Istanta.Models.Utenti", "IdUtenteNavigation")
                        .WithMany("UtentiFicos")
                        .HasForeignKey("IdUtente")
                        .HasConstraintName("PK_utenti_fico");

                    b.Navigation("IdUtenteNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcelRelazioni", b =>
                {
                    b.HasOne("Istanta.Models_2.SchemaCampiExcel", "IdCampoNavigation")
                        .WithMany("AddestramentoExcelRelazionis")
                        .HasForeignKey("IdCampoNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdCampoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboPagine", b =>
                {
                    b.HasOne("Istanta.Models_2.PromoTracciati", "IdTracciatoNavigation")
                        .WithMany("MenaboPagines")
                        .HasForeignKey("IdTracciatoNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdTracciatoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboRef", b =>
                {
                    b.HasOne("Istanta.Models_2.MenaboPagine", "IdPaginaNavigation")
                        .WithMany("MenaboRefs")
                        .HasForeignKey("IdPaginaNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Istanta.Models_2.PromoTracciatiRecord", "IdRecordNavigation")
                        .WithMany("MenaboRefs")
                        .HasForeignKey("IdRecordNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPaginaNavigation");

                    b.Navigation("IdRecordNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoImportazioni", b =>
                {
                    b.HasOne("Istanta.Models_2.AddestramentoExcel", "IdAddestramentoNavigation")
                        .WithMany("PromoImportazionis")
                        .HasForeignKey("IdAddestramentoNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Istanta.Models.Attivitum", "IdAttivitaNavigation")
                        .WithMany("PromoImportazionis")
                        .HasForeignKey("IdAttivitaNavigationId");

                    b.HasOne("Istanta.Models_2.Promo", "IdPromoNavigation")
                        .WithMany("PromoImportazionis")
                        .HasForeignKey("IdPromoNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAddestramentoNavigation");

                    b.Navigation("IdAttivitaNavigation");

                    b.Navigation("IdPromoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecord", b =>
                {
                    b.HasOne("Istanta.Models_2.PromoLavorazioni", "IdPromoLavorazioniNavigation")
                        .WithMany("PromoLavorazioniRecords")
                        .HasForeignKey("IdPromoLavorazioniNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Istanta.Models_2.PromoTracciatiRecord", "IdPromoTracciatiRecordNavigation")
                        .WithMany("PromoLavorazioniRecords")
                        .HasForeignKey("IdPromoTracciatiRecordNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPromoLavorazioniNavigation");

                    b.Navigation("IdPromoTracciatiRecordNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecordRegister", b =>
                {
                    b.HasOne("Istanta.Models_2.PromoLavorazioniRecord", "IdPromoLavorazioniRecordNavigation")
                        .WithMany("PromoLavorazioniRecordRegisters")
                        .HasForeignKey("IdPromoLavorazioniRecordNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPromoLavorazioniRecordNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciati", b =>
                {
                    b.HasOne("Istanta.Models_2.PromoImportazioni", "IdImportazioneNavigation")
                        .WithMany("PromoTracciatis")
                        .HasForeignKey("IdImportazioneNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Istanta.Models_2.Promo", "IdPromoNavigation")
                        .WithMany("PromoTracciatis")
                        .HasForeignKey("IdPromoNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdImportazioneNavigation");

                    b.Navigation("IdPromoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciatiRecord", b =>
                {
                    b.HasOne("Istanta.Models_2.AddestramentoExcel", "IdAddestramentoNavigation")
                        .WithMany("PromoTracciatiRecords")
                        .HasForeignKey("IdAddestramentoNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Istanta.Models_2.PromoTracciati", "IdTracciatoNavigation")
                        .WithMany("PromoTracciatiRecords")
                        .HasForeignKey("IdTracciatoNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAddestramentoNavigation");

                    b.Navigation("IdTracciatoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcel", b =>
                {
                    b.HasOne("Istanta.Models_2.AddestramentoExcel", "IdAddestramentoNavigation")
                        .WithMany("SchemaCampiExcels")
                        .HasForeignKey("IdAddestramentoNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAddestramentoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcelRelazioni", b =>
                {
                    b.HasOne("Istanta.Models_2.SchemaCampiExcel", "IdCampoNavigation")
                        .WithMany("SchemaCampiExcelRelazionis")
                        .HasForeignKey("IdCampoNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Istanta.Models_2.AddestramentoExcelRelazioni", "IdRelazioneNavigation")
                        .WithMany("SchemaCampiExcelRelazionis")
                        .HasForeignKey("IdRelazioneNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdCampoNavigation");

                    b.Navigation("IdRelazioneNavigation");
                });

            modelBuilder.Entity("Istanta.Models.Articoli", b =>
                {
                    b.Navigation("ArticoliDescrizionis");

                    b.Navigation("ArticoliFotos");

                    b.Navigation("FotoEscluses");
                });

            modelBuilder.Entity("Istanta.Models.Attivitum", b =>
                {
                    b.Navigation("AttivitaLogs");

                    b.Navigation("PromoImportazionis");

                    b.Navigation("SubAttivita");
                });

            modelBuilder.Entity("Istanta.Models.RegistroOperazioni", b =>
                {
                    b.Navigation("RegistroPopagazionis");
                });

            modelBuilder.Entity("Istanta.Models.Utenti", b =>
                {
                    b.Navigation("RegistroPopagazionis");

                    b.Navigation("UtentiFicos");
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcel", b =>
                {
                    b.Navigation("PromoImportazionis");

                    b.Navigation("PromoTracciatiRecords");

                    b.Navigation("SchemaCampiExcels");
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcelRelazioni", b =>
                {
                    b.Navigation("SchemaCampiExcelRelazionis");
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboPagine", b =>
                {
                    b.Navigation("MenaboRefs");
                });

            modelBuilder.Entity("Istanta.Models_2.Promo", b =>
                {
                    b.Navigation("PromoImportazionis");

                    b.Navigation("PromoTracciatis");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoImportazioni", b =>
                {
                    b.Navigation("PromoTracciatis");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioni", b =>
                {
                    b.Navigation("PromoLavorazioniRecords");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecord", b =>
                {
                    b.Navigation("PromoLavorazioniRecordRegisters");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciati", b =>
                {
                    b.Navigation("MenaboPagines");

                    b.Navigation("PromoTracciatiRecords");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciatiRecord", b =>
                {
                    b.Navigation("MenaboRefs");

                    b.Navigation("PromoLavorazioniRecords");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcel", b =>
                {
                    b.Navigation("AddestramentoExcelRelazionis");

                    b.Navigation("SchemaCampiExcelRelazionis");
                });
#pragma warning restore 612, 618
        }
    }
}
