CREATE TABLE "AddestramentoExcel" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FileAddestramento" text NOT NULL,
    "Titolo" text NULL,
    "DataCaricamento" timestamp with time zone NOT NULL,
    "esportaSubito" boolean NOT NULL,
    "salvaSuDb" boolean NOT NULL,
    "externalCallPerImport" text NULL,
    "externalCallPerExport" text NULL,
    "externalCallPerExportPoP" text NULL,
    CONSTRAINT "PK_AddestramentoExcel" PRIMARY KEY ("Id")
);


CREATE TABLE articoli (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    codice character varying(100) NOT NULL,
    descrizione1 character varying(4000) NOT NULL,
    descrizione2 character varying(4000) NOT NULL,
    descrizione3 character varying(4000) NOT NULL,
    descrizione4 character varying(4000) NOT NULL,
    peso numeric(18,3) NULL,
    um character varying(10) NULL,
    ultima_revisione timestamp without time zone NULL,
    stato_revisione smallint NOT NULL,
    nota_tecnica text NULL,
    reparto integer NULL,
    segmento character varying(20) NULL,
    ean character varying(30) NULL,
    data_inserimento timestamp without time zone NULL,
    data_modifica timestamp without time zone NULL,
    CONSTRAINT "PK_articoli" PRIMARY KEY (id)
);
COMMENT ON COLUMN articoli.stato_revisione IS '0 - non processato 1 - descrizione conad approvata 2 - descrizione conad bocciata 3 - obsoleto 4 - processato solo da edro';


CREATE TABLE "Attivita" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_parent bigint NULL,
    id_utente smallint NULL,
    coda smallint NOT NULL,
    titolo character varying(250) NOT NULL,
    contract character varying(500) NOT NULL,
    data_inserimento timestamp without time zone NOT NULL,
    tipo smallint NOT NULL DEFAULT (((1))),
    tipo_processo smallint NOT NULL DEFAULT (((1))),
    stato smallint NOT NULL,
    progress smallint NOT NULL,
    stato_msg character varying(250) NULL,
    data_fine timestamp without time zone NULL,
    data_inizio timestamp without time zone NULL,
    priorita smallint NOT NULL,
    CONSTRAINT "PK_Attivita" PRIMARY KEY (id),
    CONSTRAINT "FK_Attivita_Attivita" FOREIGN KEY (id_parent) REFERENCES "Attivita" (id)
);


CREATE TABLE "Promo" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomePromo" text NOT NULL,
    "DataRegistrazione" timestamp with time zone NOT NULL,
    "ValiditaDal" timestamp with time zone NULL,
    "ValiditaAl" timestamp with time zone NULL,
    "DataScadenza" timestamp with time zone NULL,
    "Stato" smallint NOT NULL,
    "guidID" text NULL,
    "Context" text NULL,
    CONSTRAINT "PK_Promo" PRIMARY KEY ("Id")
);


CREATE TABLE "PromoLavorazioni" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "GuidId" text NULL,
    "GuidPromo" text NULL,
    "GuidCanale" text NULL,
    "GuidArea" text NULL,
    "GuidRaccoglitore" text NULL,
    "GuidFormato" text NULL,
    "IdAutore" smallint NOT NULL,
    "RegisterDate" timestamp with time zone NOT NULL,
    "Meta" text NULL,
    "Stato" smallint NOT NULL,
    CONSTRAINT "PK_PromoLavorazioni" PRIMARY KEY ("Id")
);


CREATE TABLE registro_operazioni (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo_operazione smallint NOT NULL,
    codice_associato character varying(4000) NULL,
    "idTracciato" integer NULL,
    "idPromoLavorazione" integer NULL,
    "idPromoLavorazioniRecord" bigint NULL,
    area character varying(30) NULL,
    canale character varying(30) NULL,
    url text NULL,
    "formData" text NULL,
    data_registrazione timestamp without time zone NOT NULL,
    data_esecuzione timestamp without time zone NULL,
    data_elaborazione_propagazioni timestamp without time zone NULL,
    stato smallint NOT NULL,
    autore integer NOT NULL,
    esecutore integer NULL,
    CONSTRAINT "PK_registro_operazioni" PRIMARY KEY (id)
);


CREATE TABLE settings (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    codice character varying(80) NOT NULL,
    valore text NOT NULL,
    CONSTRAINT "PK_settings" PRIMARY KEY (id)
);


CREATE TABLE utenti (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    "nomeUtente" character varying(150) NOT NULL,
    nome character varying(150) NULL,
    cognome character varying(150) NULL,
    email character varying(150) NOT NULL,
    password character varying(50) NOT NULL,
    stato smallint NOT NULL,
    ruolo smallint NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    data_update timestamp without time zone NULL,
    "privateKey" character varying(50) NULL,
    ad_token character varying(50) NULL,
    scadenza_token_ad timestamp with time zone NULL,
    "policyGroups" character varying(150) NULL,
    CONSTRAINT "PK_utenti" PRIMARY KEY (id)
);


CREATE TABLE "SchemaCampiExcel" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdAddestramento" integer NOT NULL,
    "NomeColonnaOriginale" text NOT NULL,
    "Indice" smallint NOT NULL,
    "NomeColonna" text NULL,
    "NomeVisualizzato" text NULL,
    "Note" text NULL,
    "TipoDato" smallint NULL,
    "Ruolo" text NULL,
    "Ordinamento" smallint NULL,
    "IdAddestramentoNavigationId" integer NOT NULL,
    CONSTRAINT "PK_SchemaCampiExcel" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SchemaCampiExcel_AddestramentoExcel_IdAddestramentoNavigati~" FOREIGN KEY ("IdAddestramentoNavigationId") REFERENCES "AddestramentoExcel" ("Id") ON DELETE CASCADE
);


CREATE TABLE articoli_descrizioni (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_articolo bigint NULL,
    codice_gruppo text NULL,
    area character varying(30) NULL,
    canale character varying(30) NULL,
    custom character varying(1000) NULL,
    descrizione_1 character varying(4000) NULL,
    descrizione_2 character varying(4000) NULL,
    descrizione_3 character varying(4000) NULL,
    descrizione_4 character varying(4000) NULL,
    descrizione_indd character varying(4000) NULL,
    extra text NULL,
    peso numeric(18,3) NULL,
    um text NULL,
    data_ultima_ricezione timestamp without time zone NOT NULL,
    approvata boolean NOT NULL,
    attiva boolean NOT NULL,
    firma_tracciato text NULL,
    meta text NULL,
    CONSTRAINT "PK_articoli_descrizioni" PRIMARY KEY (id),
    CONSTRAINT "FK_articoli_descrizioni_articoli" FOREIGN KEY (id_articolo) REFERENCES articoli (id)
);


CREATE TABLE articoli_foto (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_articolo bigint NOT NULL,
    area character varying(30) NULL,
    canale character varying(30) NULL,
    path_foto character varying(250) NOT NULL,
    nome_reale character varying(250) NOT NULL,
    guid_id character varying(50) NOT NULL,
    puntatore boolean NOT NULL,
    data_inserimento timestamp without time zone NOT NULL,
    stato_selezione smallint NULL DEFAULT (((1))),
    attiva boolean NOT NULL DEFAULT true,
    hash character varying(200) NULL,
    data_modifica timestamp without time zone NULL,
    tipo smallint NULL,
    CONSTRAINT "PK_articoli_foto" PRIMARY KEY (id),
    CONSTRAINT "FK_articoli_foto_articoli" FOREIGN KEY (id_articolo) REFERENCES articoli (id)
);
COMMENT ON COLUMN articoli_foto.stato_selezione IS '0 - no selezionata 1 - primaria 2 - selezionata';


CREATE TABLE foto_escluse (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "idArticolo" bigint NOT NULL,
    nome_reale character varying(250) NOT NULL,
    data_inserimento timestamp without time zone NOT NULL,
    "Filtro" text NULL,
    CONSTRAINT "PK_foto_escluse" PRIMARY KEY (id),
    CONSTRAINT "FK_foto_escluse_articoli" FOREIGN KEY ("idArticolo") REFERENCES articoli (id)
);


CREATE TABLE "AttivitaLogs" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_attivita bigint NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    tipo smallint NOT NULL,
    note text NOT NULL,
    CONSTRAINT "PK_AttivitaLogs" PRIMARY KEY (id),
    CONSTRAINT "FK_AttivitaLogs_Attivita" FOREIGN KEY (id_attivita) REFERENCES "Attivita" (id)
);


CREATE TABLE "PromoImportazioni" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdAddestramento" integer NOT NULL,
    "IdPromo" integer NOT NULL,
    "NomeFile" text NOT NULL,
    "TipoMateriale" text NULL,
    "DataCaricamento" timestamp with time zone NOT NULL,
    "ParamsRequest" text NULL,
    "guidID" text NULL,
    "IdAttivita" bigint NULL,
    "IdAddestramentoNavigationId" integer NOT NULL,
    "IdPromoNavigationId" integer NOT NULL,
    "IdAttivitaNavigationId" bigint NULL,
    CONSTRAINT "PK_PromoImportazioni" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PromoImportazioni_AddestramentoExcel_IdAddestramentoNavigat~" FOREIGN KEY ("IdAddestramentoNavigationId") REFERENCES "AddestramentoExcel" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PromoImportazioni_Attivita_IdAttivitaNavigationId" FOREIGN KEY ("IdAttivitaNavigationId") REFERENCES "Attivita" (id),
    CONSTRAINT "FK_PromoImportazioni_Promo_IdPromoNavigationId" FOREIGN KEY ("IdPromoNavigationId") REFERENCES "Promo" ("Id") ON DELETE CASCADE
);


CREATE TABLE registro_propagazioni (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "idRegistro" bigint NOT NULL,
    "idPromoLavorazioneRecord" bigint NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    data_elaborazione timestamp without time zone NULL,
    autore_elaborazione smallint NULL,
    priorita smallint NOT NULL,
    stato smallint NOT NULL,
    CONSTRAINT "PK_registro_propagazioni" PRIMARY KEY (id),
    CONSTRAINT "FK_registro_propagazioni_registro_operazioni" FOREIGN KEY ("idRegistro") REFERENCES registro_operazioni (id) ON DELETE CASCADE,
    CONSTRAINT "FK_registro_propagazioni_utenti" FOREIGN KEY (autore_elaborazione) REFERENCES utenti (id)
);


CREATE TABLE utenti_fico (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_utente smallint NULL,
    token character varying(100) NOT NULL,
    origin character varying(50) NOT NULL,
    username character varying(150) NOT NULL,
    tipo_utente smallint NOT NULL,
    user_data text NOT NULL,
    last_access timestamp without time zone NOT NULL,
    CONSTRAINT "PK_utenti_fico" PRIMARY KEY (id),
    CONSTRAINT "FK_utenti_fico_utenti" FOREIGN KEY (id_utente) REFERENCES utenti (id)
);


CREATE TABLE "AddestramentoExcelRelazioni" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdCampo" bigint NOT NULL,
    "NomeRelazione" text NOT NULL,
    "Algoritmo" text NULL,
    "TipoCompilazione" smallint NOT NULL,
    "IdCampoNavigationId" bigint NOT NULL,
    CONSTRAINT "PK_AddestramentoExcelRelazioni" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AddestramentoExcelRelazioni_SchemaCampiExcel_IdCampoNavigat~" FOREIGN KEY ("IdCampoNavigationId") REFERENCES "SchemaCampiExcel" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PromoTracciati" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IdImportazione" integer NOT NULL,
    "IdPromo" integer NOT NULL,
    "Versione" smallint NOT NULL,
    "Sigla" text NULL,
    "guidArea" text NULL,
    "guidCanale" text NULL,
    "guidPV" text NULL,
    "Area" text NULL,
    "Canale" text NULL,
    "OrdineLista" text NULL,
    "Meta" text NULL,
    "Context" text NULL,
    "IdImportazioneNavigationId" integer NOT NULL,
    "IdPromoNavigationId" integer NOT NULL,
    CONSTRAINT "PK_PromoTracciati" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PromoTracciati_Promo_IdPromoNavigationId" FOREIGN KEY ("IdPromoNavigationId") REFERENCES "Promo" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PromoTracciati_PromoImportazioni_IdImportazioneNavigationId" FOREIGN KEY ("IdImportazioneNavigationId") REFERENCES "PromoImportazioni" ("Id") ON DELETE CASCADE
);


CREATE TABLE "SchemaCampiExcelRelazioni" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdRelazione" integer NOT NULL,
    "IdCampo" bigint NOT NULL,
    "Condizione" text NULL,
    "IdCampoNavigationId" bigint NOT NULL,
    "IdRelazioneNavigationId" integer NOT NULL,
    CONSTRAINT "PK_SchemaCampiExcelRelazioni" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SchemaCampiExcelRelazioni_AddestramentoExcelRelazioni_IdRel~" FOREIGN KEY ("IdRelazioneNavigationId") REFERENCES "AddestramentoExcelRelazioni" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_SchemaCampiExcelRelazioni_SchemaCampiExcel_IdCampoNavigatio~" FOREIGN KEY ("IdCampoNavigationId") REFERENCES "SchemaCampiExcel" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MenaboPagine" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdTracciato" integer NOT NULL,
    "Numero" smallint NOT NULL,
    "Formato" text NULL,
    "IdMastro" smallint NOT NULL,
    "IdTracciatoNavigationId" integer NOT NULL,
    CONSTRAINT "PK_MenaboPagine" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MenaboPagine_PromoTracciati_IdTracciatoNavigationId" FOREIGN KEY ("IdTracciatoNavigationId") REFERENCES "PromoTracciati" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PromoTracciatiRecord" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdTracciato" integer NOT NULL,
    "Versione" smallint NOT NULL,
    "IndiceLettura" integer NOT NULL,
    "IndiceEsportazione" integer NOT NULL,
    "Label" text NULL,
    "Scatto" text NULL,
    "Codice" text NULL,
    "CodiceGruppo" text NULL,
    "Dato" text NULL,
    "DaEsportare" boolean NULL,
    "IdAddestramento" integer NULL,
    "DataRegistrazione" timestamp with time zone NULL,
    "ModalitaInserimento" smallint NOT NULL,
    "Stato" smallint NOT NULL,
    "IdTracciatoNavigationId" integer NOT NULL,
    "IdAddestramentoNavigationId" integer NOT NULL,
    CONSTRAINT "PK_PromoTracciatiRecord" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PromoTracciatiRecord_AddestramentoExcel_IdAddestramentoNavi~" FOREIGN KEY ("IdAddestramentoNavigationId") REFERENCES "AddestramentoExcel" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PromoTracciatiRecord_PromoTracciati_IdTracciatoNavigationId" FOREIGN KEY ("IdTracciatoNavigationId") REFERENCES "PromoTracciati" ("Id") ON DELETE CASCADE
);


CREATE TABLE "MenaboRef" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdRecord" bigint NULL,
    "CodiceGruppo" text NULL,
    "IdPagina" bigint NOT NULL,
    "Indice" smallint NOT NULL,
    "Selezione" smallint NOT NULL,
    "Formato" text NULL,
    "Meccaniche" text NULL,
    "IdPaginaNavigationId" bigint NOT NULL,
    "IdRecordNavigationId" bigint NOT NULL,
    CONSTRAINT "PK_MenaboRef" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_MenaboRef_MenaboPagine_IdPaginaNavigationId" FOREIGN KEY ("IdPaginaNavigationId") REFERENCES "MenaboPagine" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_MenaboRef_PromoTracciatiRecord_IdRecordNavigationId" FOREIGN KEY ("IdRecordNavigationId") REFERENCES "PromoTracciatiRecord" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PromoLavorazioniRecord" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdLavorazione" integer NOT NULL,
    "IdRecordTracciato" bigint NOT NULL,
    "Codice" text NULL,
    "CodiceGruppo" text NULL,
    "IdAutore" smallint NOT NULL,
    "RegisterDate" timestamp with time zone NULL,
    "Indice" smallint NOT NULL,
    "Pagina" smallint NOT NULL,
    "Meta" text NULL,
    "IdPromoLavorazioniNavigationId" integer NOT NULL,
    "IdPromoTracciatiRecordNavigationId" bigint NOT NULL,
    CONSTRAINT "PK_PromoLavorazioniRecord" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PromoLavorazioniRecord_PromoLavorazioni_IdPromoLavorazioniN~" FOREIGN KEY ("IdPromoLavorazioniNavigationId") REFERENCES "PromoLavorazioni" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_PromoLavorazioniRecord_PromoTracciatiRecord_IdPromoTracciat~" FOREIGN KEY ("IdPromoTracciatiRecordNavigationId") REFERENCES "PromoTracciatiRecord" ("Id") ON DELETE CASCADE
);


CREATE TABLE "PromoLavorazioniRecordRegister" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdLavorazioneRecord" bigint NOT NULL,
    "IdAutore" smallint NOT NULL,
    "TipoAzione" smallint NOT NULL,
    "RegisterDate" timestamp with time zone NULL,
    "IdPromoLavorazioniRecordNavigationId" bigint NOT NULL,
    CONSTRAINT "PK_PromoLavorazioniRecordRegister" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PromoLavorazioniRecordRegister_PromoLavorazioniRecord_IdPro~" FOREIGN KEY ("IdPromoLavorazioniRecordNavigationId") REFERENCES "PromoLavorazioniRecord" ("Id") ON DELETE CASCADE
);


CREATE INDEX "IX_AddestramentoExcelRelazioni_IdCampoNavigationId" ON "AddestramentoExcelRelazioni" ("IdCampoNavigationId");


CREATE INDEX "IX_articoli_descrizioni_id_articolo" ON articoli_descrizioni (id_articolo);


CREATE INDEX "IX_articoli_foto_id_articolo" ON articoli_foto (id_articolo);


CREATE INDEX "IX_Attivita_id_parent" ON "Attivita" (id_parent);


CREATE INDEX "IX_AttivitaLogs_id_attivita" ON "AttivitaLogs" (id_attivita);


CREATE INDEX "IX_foto_escluse_idArticolo" ON foto_escluse ("idArticolo");


CREATE INDEX "IX_MenaboPagine_IdTracciatoNavigationId" ON "MenaboPagine" ("IdTracciatoNavigationId");


CREATE INDEX "IX_MenaboRef_IdPaginaNavigationId" ON "MenaboRef" ("IdPaginaNavigationId");


CREATE INDEX "IX_MenaboRef_IdRecordNavigationId" ON "MenaboRef" ("IdRecordNavigationId");


CREATE INDEX "IX_PromoImportazioni_IdAddestramentoNavigationId" ON "PromoImportazioni" ("IdAddestramentoNavigationId");


CREATE INDEX "IX_PromoImportazioni_IdAttivitaNavigationId" ON "PromoImportazioni" ("IdAttivitaNavigationId");


CREATE INDEX "IX_PromoImportazioni_IdPromoNavigationId" ON "PromoImportazioni" ("IdPromoNavigationId");


CREATE INDEX "IX_PromoLavorazioniRecord_IdPromoLavorazioniNavigationId" ON "PromoLavorazioniRecord" ("IdPromoLavorazioniNavigationId");


CREATE INDEX "IX_PromoLavorazioniRecord_IdPromoTracciatiRecordNavigationId" ON "PromoLavorazioniRecord" ("IdPromoTracciatiRecordNavigationId");


CREATE INDEX "IX_PromoLavorazioniRecordRegister_IdPromoLavorazioniRecordNavi~" ON "PromoLavorazioniRecordRegister" ("IdPromoLavorazioniRecordNavigationId");


CREATE INDEX "IX_PromoTracciati_IdImportazioneNavigationId" ON "PromoTracciati" ("IdImportazioneNavigationId");


CREATE INDEX "IX_PromoTracciati_IdPromoNavigationId" ON "PromoTracciati" ("IdPromoNavigationId");


CREATE INDEX "IX_PromoTracciatiRecord_IdAddestramentoNavigationId" ON "PromoTracciatiRecord" ("IdAddestramentoNavigationId");


CREATE INDEX "IX_PromoTracciatiRecord_IdTracciatoNavigationId" ON "PromoTracciatiRecord" ("IdTracciatoNavigationId");


CREATE INDEX "IX_registro_propagazioni_autore_elaborazione" ON registro_propagazioni (autore_elaborazione);


CREATE INDEX "IX_registro_propagazioni_idRegistro" ON registro_propagazioni ("idRegistro");


CREATE INDEX "IX_SchemaCampiExcel_IdAddestramentoNavigationId" ON "SchemaCampiExcel" ("IdAddestramentoNavigationId");


CREATE INDEX "IX_SchemaCampiExcelRelazioni_IdCampoNavigationId" ON "SchemaCampiExcelRelazioni" ("IdCampoNavigationId");


CREATE INDEX "IX_SchemaCampiExcelRelazioni_IdRelazioneNavigationId" ON "SchemaCampiExcelRelazioni" ("IdRelazioneNavigationId");


CREATE UNIQUE INDEX "IX_utenti_email" ON utenti (email);


CREATE INDEX "IX_utenti_fico_id_utente" ON utenti_fico (id_utente);


