CREATE TABLE addestramento_excel (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    file_addestramento character varying(150) NOT NULL,
    titolo character varying(100) NULL,
    data_caricamento timestamp without time zone NOT NULL,
    "esportaSubito" boolean NOT NULL,
    "salvaSuDb" boolean NOT NULL,
    "externalCallPerImport" text NULL,
    "externalCallPerExport" text NULL,
    "externalCallPerExportPoP" text NULL,
    CONSTRAINT "PK_addestramento_excel" PRIMARY KEY (id)
);


CREATE TABLE "Attivitum" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdParent" bigint NULL,
    "IdUtente" smallint NULL,
    "Coda" smallint NOT NULL,
    "Titolo" text NOT NULL,
    "Contract" text NOT NULL,
    "DataInserimento" timestamp with time zone NOT NULL,
    "Tipo" smallint NOT NULL,
    "TipoProcesso" smallint NOT NULL,
    "Stato" smallint NOT NULL,
    "Progress" smallint NOT NULL,
    "StatoMsg" text NULL,
    "DataFine" timestamp with time zone NULL,
    "DataInizio" timestamp with time zone NULL,
    "Priorita" smallint NOT NULL,
    "IdParentNavigationId" bigint NULL,
    CONSTRAINT "PK_Attivitum" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Attivitum_Attivitum_IdParentNavigationId" FOREIGN KEY ("IdParentNavigationId") REFERENCES "Attivitum" ("Id")
);


CREATE TABLE promo (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome_promo character varying(100) NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    validita_dal timestamp without time zone NULL,
    validita_al timestamp without time zone NULL,
    data_scadenza timestamp without time zone NULL,
    stato smallint NOT NULL DEFAULT (((1))),
    "guidId" character varying(50) NULL,
    context text NULL,
    CONSTRAINT "PK_promo" PRIMARY KEY (id)
);
COMMENT ON COLUMN promo.stato IS '0-chiusa 1-aperta';


CREATE TABLE promo_lavorazioni (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "guidId" text NULL,
    "guidPromo" text NULL,
    "guidCanale" text NULL,
    "guidArea" text NULL,
    "guidRaccoglitore" text NULL,
    "guidFormato" text NULL,
    id_autore smallint NOT NULL,
    register_date timestamp without time zone NOT NULL,
    meta text NULL,
    stato smallint NOT NULL,
    CONSTRAINT "PK_promo_lavorazioni" PRIMARY KEY (id)
);


CREATE TABLE schema_custom (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    titolo character varying(60) NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    CONSTRAINT "PK_schema_custom" PRIMARY KEY (id)
);


CREATE TABLE schema_campi_excel (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_addestramento integer NOT NULL,
    nome_colonna_originale character varying(70) NOT NULL,
    indice smallint NOT NULL,
    nome_colonna character varying(70) NULL,
    nome_visualizzato character varying(70) NULL,
    note character varying(500) NULL,
    tipo_dato smallint NULL,
    ruolo character varying(100) NULL,
    ordinamento smallint NULL DEFAULT (((0))),
    CONSTRAINT "PK_schema_campi_excel" PRIMARY KEY (id),
    CONSTRAINT "FK_schema_campi_excel_addestramento_excel" FOREIGN KEY (id_addestramento) REFERENCES addestramento_excel (id)
);
COMMENT ON COLUMN schema_campi_excel.ordinamento IS '0 - none 1 - categoria(liv1) 2 - reparto (liv2) 3 - settore (liv 3) 4 - segmento (liv 4)';


CREATE TABLE "AttivitaLog" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdAttivita" bigint NOT NULL,
    "DataRegistrazione" timestamp with time zone NOT NULL,
    "Tipo" smallint NOT NULL,
    "Note" text NOT NULL,
    "IdAttivitaNavigationId" bigint NOT NULL,
    CONSTRAINT "PK_AttivitaLog" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AttivitaLog_Attivitum_IdAttivitaNavigationId" FOREIGN KEY ("IdAttivitaNavigationId") REFERENCES "Attivitum" ("Id") ON DELETE CASCADE
);


CREATE TABLE promo_importazioni (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_addestramento integer NOT NULL,
    id_promo integer NOT NULL,
    nome_file character varying(150) NOT NULL,
    tipo_materiale character varying(50) NULL,
    data_caricamento timestamp without time zone NOT NULL,
    "paramsRequest" text NULL,
    "guidId" character varying(50) NULL,
    id_attivita bigint NULL,
    CONSTRAINT "PK_promo_importazioni" PRIMARY KEY (id),
    CONSTRAINT "FK_promo_importazioni_addestramento_excel" FOREIGN KEY (id_addestramento) REFERENCES addestramento_excel (id),
    CONSTRAINT "FK_promo_importazioni_Attivita" FOREIGN KEY (id_attivita) REFERENCES "Attivitum" ("Id"),
    CONSTRAINT "FK_promo_importazioni_promo" FOREIGN KEY (id_promo) REFERENCES promo (id)
);


CREATE TABLE schema_custom_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_schema smallint NOT NULL,
    dato text NOT NULL,
    CONSTRAINT "PK_schema_custom_records" PRIMARY KEY (id),
    CONSTRAINT "FK_schema_custom_records_schema_custom" FOREIGN KEY (id_schema) REFERENCES schema_custom (id)
);


CREATE TABLE addestramento_excel_relazioni (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_campo bigint NOT NULL,
    nome_relazione character varying(50) NOT NULL,
    algoritmo text NULL,
    tipo_compilazione smallint NOT NULL DEFAULT (((1))),
    CONSTRAINT "PK_addestramento_excel_relazioni" PRIMARY KEY (id),
    CONSTRAINT "FK_addestramento_excel_relazioni_schema_campi_excel" FOREIGN KEY (id_campo) REFERENCES schema_campi_excel (id)
);
COMMENT ON COLUMN addestramento_excel_relazioni.id_campo IS 'Rif al campo esteso, non trovato nell''excel';
COMMENT ON COLUMN addestramento_excel_relazioni.tipo_compilazione IS '1 - importazione inline 2 - importazione atend  3 - esportazione 4 - Manuale';


CREATE TABLE promo_tracciati (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_importazione integer NOT NULL,
    id_promo integer NOT NULL,
    versione smallint NOT NULL,
    sigla character varying(50) NULL,
    "guidArea" character varying(50) NULL,
    "guidCanale" character varying(50) NULL,
    "guidPV" character varying(50) NULL,
    area text NULL,
    canale text NULL,
    ordine_lista text NULL,
    meta text NULL,
    context text NULL,
    CONSTRAINT "PK_promo_tracciati" PRIMARY KEY (id),
    CONSTRAINT "FK_promo_tracciati_promo" FOREIGN KEY (id_promo) REFERENCES promo (id),
    CONSTRAINT "FK_promo_tracciati_promo_importazioni" FOREIGN KEY (id_importazione) REFERENCES promo_importazioni (id)
);


CREATE TABLE schema_campi_excel_relazioni (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_relazione integer NOT NULL,
    id_campo bigint NOT NULL,
    condizione character varying(500) NULL,
    CONSTRAINT "PK_schema_campi_excel_relazioni" PRIMARY KEY (id),
    CONSTRAINT "FK_schema_campi_excel_relazioni_addestramento_excel_relazioni" FOREIGN KEY (id_relazione) REFERENCES addestramento_excel_relazioni (id),
    CONSTRAINT "FK_schema_campi_excel_relazioni_schema_campi_excel" FOREIGN KEY (id_campo) REFERENCES schema_campi_excel (id)
);
COMMENT ON COLUMN schema_campi_excel_relazioni.id_campo IS 'Rif al campo essitente sull''excel';


CREATE TABLE menabo_pagine (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_tracciato integer NOT NULL,
    numero smallint NOT NULL,
    formato character varying(15) NULL,
    id_mastro smallint NOT NULL,
    CONSTRAINT "PK_menabo_pagine" PRIMARY KEY (id),
    CONSTRAINT "FK_menabo_pagine_promo_tracciati" FOREIGN KEY (id_tracciato) REFERENCES promo_tracciati (id)
);


CREATE TABLE promo_tracciati_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_tracciato integer NOT NULL,
    versione smallint NOT NULL,
    indice_lettura integer NOT NULL,
    indice_esportazione integer NOT NULL DEFAULT (((-1))),
    label character varying(40) NULL,
    scatto character varying(500) NULL,
    codice character varying(100) NULL,
    codice_gruppo character varying(4000) NULL,
    dato text NULL,
    da_esportare boolean NULL,
    id_addestramento integer NULL,
    data_registrazione timestamp without time zone NULL,
    modalita_inserimento smallint NOT NULL,
    stato smallint NOT NULL,
    CONSTRAINT "PK_promo_tracciati_records" PRIMARY KEY (id),
    CONSTRAINT "FK_promo_importazioni_Attivita" FOREIGN KEY (id_addestramento) REFERENCES addestramento_excel (id),
    CONSTRAINT "FK_promo_tracciati_records_promo_tracciati" FOREIGN KEY (id_tracciato) REFERENCES promo_tracciati (id)
);


CREATE TABLE menabo_ref (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_record bigint NULL,
    codice_gruppo character varying(2000) NULL,
    id_pagina bigint NOT NULL,
    indice smallint NOT NULL,
    selezione smallint NOT NULL,
    formato character varying(100) NULL,
    meccanica text NULL,
    CONSTRAINT "PK_menabo_ref" PRIMARY KEY (id),
    CONSTRAINT "FK_menabo_promo_tracciati_records" FOREIGN KEY (id_record) REFERENCES promo_tracciati_records (id),
    CONSTRAINT "FK_menabo_ref_menabo_pagine" FOREIGN KEY (id_pagina) REFERENCES menabo_pagine (id)
);


CREATE TABLE promo_lavorazioni_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_lavorazione integer NOT NULL,
    id_record_tracciato bigint NOT NULL,
    codice text NULL,
    codice_gruppo character varying(4000) NULL,
    id_autore smallint NOT NULL,
    register_date timestamp without time zone NULL,
    indice smallint NOT NULL,
    pagina smallint NOT NULL,
    meta text NULL,
    CONSTRAINT "PK_promo_lavorazioni_records" PRIMARY KEY (id),
    CONSTRAINT "FK_promo_lavorazioni_records_promo_lavorazioni" FOREIGN KEY (id_lavorazione) REFERENCES promo_lavorazioni (id),
    CONSTRAINT "FK_promo_lavorazioni_records_promo_tracciati_records" FOREIGN KEY (id_record_tracciato) REFERENCES promo_tracciati_records (id)
);


CREATE TABLE "PromoLavorazioniRecordRegister" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "IdLavorazioneRecord" bigint NOT NULL,
    "IdAutore" smallint NOT NULL,
    "TipoAzione" smallint NOT NULL,
    "RegisterDate" timestamp with time zone NULL,
    "IdPromoLavorazioniRecordNavigationId" bigint NOT NULL,
    CONSTRAINT "PK_PromoLavorazioniRecordRegister" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_PromoLavorazioniRecordRegister_promo_lavorazioni_records_Id~" FOREIGN KEY ("IdPromoLavorazioniRecordNavigationId") REFERENCES promo_lavorazioni_records (id) ON DELETE CASCADE
);


CREATE INDEX "IX_addestramento_excel_relazioni_id_campo" ON addestramento_excel_relazioni (id_campo);


CREATE INDEX "IX_AttivitaLog_IdAttivitaNavigationId" ON "AttivitaLog" ("IdAttivitaNavigationId");


CREATE INDEX "IX_Attivitum_IdParentNavigationId" ON "Attivitum" ("IdParentNavigationId");


CREATE INDEX "IX_menabo_pagine_id_tracciato" ON menabo_pagine (id_tracciato);


CREATE INDEX "IX_menabo_ref_id_pagina" ON menabo_ref (id_pagina);


CREATE INDEX "IX_menabo_ref_id_record" ON menabo_ref (id_record);


CREATE INDEX "IX_promo_importazioni_id_addestramento" ON promo_importazioni (id_addestramento);


CREATE INDEX "IX_promo_importazioni_id_attivita" ON promo_importazioni (id_attivita);


CREATE INDEX "IX_promo_importazioni_id_promo" ON promo_importazioni (id_promo);


CREATE INDEX "IX_promo_lavorazioni_records_id_lavorazione" ON promo_lavorazioni_records (id_lavorazione);


CREATE INDEX "IX_promo_lavorazioni_records_id_record_tracciato" ON promo_lavorazioni_records (id_record_tracciato);


CREATE INDEX "IX_promo_tracciati_id_importazione" ON promo_tracciati (id_importazione);


CREATE INDEX "IX_promo_tracciati_id_promo" ON promo_tracciati (id_promo);


CREATE INDEX "IX_promo_tracciati_records_id_addestramento" ON promo_tracciati_records (id_addestramento);


CREATE INDEX "IX_promo_tracciati_records_id_tracciato" ON promo_tracciati_records (id_tracciato);


CREATE INDEX "IX_PromoLavorazioniRecordRegister_IdPromoLavorazioniRecordNavi~" ON "PromoLavorazioniRecordRegister" ("IdPromoLavorazioniRecordNavigationId");


CREATE INDEX "IX_schema_campi_excel_id_addestramento" ON schema_campi_excel (id_addestramento);


CREATE INDEX "IX_schema_campi_excel_relazioni_id_campo" ON schema_campi_excel_relazioni (id_campo);


CREATE INDEX "IX_schema_campi_excel_relazioni_id_relazione" ON schema_campi_excel_relazioni (id_relazione);


CREATE INDEX "IX_schema_custom_records_id_schema" ON schema_custom_records (id_schema);


