/**
 * Codici di errore standardizzati per l'applicazione
 * Formato: [AREA]_[NUMERO] (es. USR_001)
 */
export const ErrorCodes = {
  // Domain errors
  VALIDATION_FAILED: 'DOM_001',
  BUSINESS_RULE_VIOLATION: 'DOM_002',

  // User domain
  USER_NOT_FOUND: 'USR_001',
  USER_ALREADY_EXISTS: 'USR_002',
  INVALID_CREDENTIALS: 'USR_003',

  // Application errors
  INVALID_REQUEST: 'APP_001',
  UNAUTHORIZED: 'APP_002',
  FORBIDDEN: 'APP_003',
  RATE_LIMIT_EXCEEDED: 'APP_004',

  // Infrastructure errors
  DATABASE_ERROR: 'INF_001',
  EXTERNAL_API_ERROR: 'INF_002',
  NETWORK_ERROR: 'INF_003',
  CACHE_ERROR: 'INF_004',
  SERVICE_UNAVAILABLE: 'INF_005',

  // Promotions
  PROMO_NOT_FOUND: 'PRM_001',
  PROMO_ALREADY_EXISTS: 'PRM_002',
  PROMO_INVALID_STATE: 'PRM_003',

  // WhatsApp
  WA_CREDENTIALS_MISSING: 'WA_001',
  WA_TEMPLATE_NOT_FOUND: 'WA_002',
  WA_CAMPAIGN_FAILED: 'WA_003',
  WA_NO_USERS_FOUND: 'WA_004',
  WA_PRESET_NOT_FOUND: 'WA_005',
  WA_BROADCAST_FAILED: 'WA_006',

  // Design Kit
  KIT_NOT_FOUND: 'KIT_001',
  KIT_ALREADY_DELETED: 'KIT_002',
  KIT_ALREADY_PUBLISHED: 'KIT_003',
  KIT_ALREADY_IN_REVISION: 'KIT_004',
  KIT_INVALID_STATE: 'KIT_005',

  // Runtime Kit
  RUNTIME_NOT_FOUND: 'RTK_001',
  RUNTIME_ALREADY_DELETED: 'RTK_002',
  RUNTIME_INVALID_STATE: 'RTK_003',

  // File Management
  FILE_NOT_FOUND: 'FIL_001',
  FILE_UPLOAD_FAILED: 'FIL_002',
  FILE_INVALID_FORMAT: 'FIL_003',
  FILE_GUID_EMPTY: 'FIL_004',

  // Print Orders (Ordini di Stampa)
  ORDER_NOT_FOUND: 'ORD_001',
  ORDER_INVALID_STATE: 'ORD_002',

  // Referenze
  REF_NOT_FOUND: 'REF_001',
  REF_INVALID_DATA: 'REF_002',

  // Configuration
  CONFIG_NOT_FOUND: 'CFG_001',
  CONFIG_INVALID: 'CFG_002',

  // Ephemeral Token / External API
  EPH_CHALLENGE_EXPIRED: 'EPH_001',
  EPH_TOKEN_INVALID: 'EPH_002',
  EPH_TOKEN_EXPIRED: 'EPH_003',
  EPH_ORIGIN_DENIED: 'EPH_004',
  EPH_SIGNATURE_INVALID: 'EPH_005',

  // CSRF / Security
  CSRF_TOKEN_MISSING: 'SEC_001',
  CSRF_TOKEN_INVALID: 'SEC_002',
  CSRF_TOKEN_EXPIRED: 'SEC_003',

  // OIDC
  OIDC_PROVIDER_ERROR: 'OIDC_001',
  OIDC_CALLBACK_FAILED: 'OIDC_002',

  // GPT / AI
  GPT_SERVICE_ERROR: 'AI_001',
  GPT_RATE_LIMIT: 'AI_002',

  // GDO
  GDO_NOT_FOUND: 'GDO_001',

  // Email
  EMAIL_SEND_FAILED: 'EML_001',
  EMAIL_TOKEN_INVALID: 'EML_002',
  EMAIL_TOKEN_EXPIRED: 'EML_003',

  // Formato
  FORMATO_NOT_FOUND: 'FMT_001',

  // Naming Convention
  NAMING_CONV_NOT_FOUND: 'NMC_001',

  // Tipo Export
  TIPO_EXPORT_NOT_FOUND: 'TEX_001',

  // WebPliant
  WPL_WORKSPACE_NOT_FOUND: 'WPL_001',

  // Punto Vendita
  PV_NOT_FOUND: 'PV_001',
  PV_INVALID_DATA: 'PV_002',

  // Area / Canale
  AREA_NOT_FOUND: 'ARC_001',
  CANALE_NOT_FOUND: 'ARC_002',

  // Tracciato
  TRACCIATO_NOT_FOUND: 'TRC_001',
  TRACCIATO_INVALID: 'TRC_002',

  // Webhook
  WEBHOOK_NOT_FOUND: 'WHK_001',
  WEBHOOK_DELIVERY_FAILED: 'WHK_002',

  // Contratto Tipografia
  CONTRATTO_NOT_FOUND: 'CTR_001',

  // Raccoglitore Kit
  RACCOGLITORE_NOT_FOUND: 'RCK_001',

  // Attivita
  ATTIVITA_NOT_FOUND: 'ATV_001',

  // Menu
  MENU_NOT_FOUND: 'MNU_001',
  MENU_CACHE_ERROR: 'MNU_002',
} as const;

export type ErrorCode = typeof ErrorCodes[keyof typeof ErrorCodes];
