
enum SSE_UPLOAD_STATE {
    STARTING = 'STARTING',
    DOWNLOAD_STARTED = 'DOWNLOAD_STARTED',
    DOWNLOADING = 'DOWNLOADING',
    DOWNLOAD_COMPLETED = 'DOWNLOAD_COMPLETED',
    DECOMPRESS_STARTED = 'DECOMPRESS_STARTED',
    DECOMPRESSING = 'DECOMPRESSING',
    DECOMPRESS_COMPLETED = 'DECOMPRESS_COMPLETED',
    IMAGE_REWORK_STARTED = 'IMAGE_REWORK_STARTED',
    REWORKING_IMAGES = 'REWORKING_IMAGES',
    IMAGE_REWORK_COMPLETED = 'IMAGE_REWORK_COMPLETED',
}


enum ABSOLUTE_PATH_TYPE {
    WEB = 'WEB',
    ARCHIVIO = 'ARCHIVIO',
    MATERIALI = 'MATERIALI',
    ALTRO = 'ALTRO',
    VIDEO = 'VIDEO',
}

enum FICO_ORIGIN {
    FP = 'FP',
    IS = 'IS',
    CO = 'CO',
    OL = 'OL',
}



enum TIPO_UTENTE_FICO_FINALE {
    SUPERADMIN = "Superadmin",
    AGENZIA = "Agenzia",
    GUEST = "Guest",
    PUNTOVENDITA = "PuntoVendita",
    GDO = "GDO",
    CATEGORY = "Category",
    MARKETING = "Marketing",
    IT = "IT",
}

export { ABSOLUTE_PATH_TYPE, FICO_ORIGIN, SSE_UPLOAD_STATE, TIPO_UTENTE_FICO_FINALE }; // esporta il modello FotoReferenze per poterlo usare in altri file
