import { STATO_UTENTI, TIPO_UTENTI, UTENTE_GENERE } from '../../../lib/enums';
import { UtenteAttributes, UtentiMeta } from '../../../lib/types';
import { CanaliInterazioneResponseDTO } from './CanaliInterazioneDTO';

/**
 * DTO per la creazione di un nuovo utente
 */
export interface CreateUtenteDTO {
  outsider?: boolean;
  nome: string;
  cognome: string;
  email: string;
  password: string;
  datadinascita?: Date;
  residenza?: string;
  tipo: TIPO_UTENTI;
  stato?: STATO_UTENTI;
  sesso?: UTENTE_GENERE;
  privatekey?: string;
  telefono?: string;
  meta?: UtentiMeta;
}

/**
 * DTO per l'aggiornamento di un utente esistente
 */
export interface UpdateUtenteDTO {
  outsider?: boolean;
  nome?: string;
  cognome?: string;
  email?: string;
  password?: string;
  datadinascita?: Date;
  residenza?: string;
  tipo?: TIPO_UTENTI;
  stato?: STATO_UTENTI;
  sesso?: UTENTE_GENERE;
  privatekey?: string;
  telefono?: string;
  meta?: UtentiMeta;
}

/**
 * DTO per la risposta con i dati dell'utente (senza password)
 */
export interface UtenteResponseDTO {
  id: string;
  outsider: boolean;
  nome: string;
  cognome: string;
  email: string;
  datadinascita?: Date;
  residenza?: string;
  tipo: TIPO_UTENTI;
  stato: STATO_UTENTI;
  sesso?: UTENTE_GENERE;
  telefono?: string;
  private_key?: string;
  createdat?: Date;
  updatedat: Date;
  meta?: UtentiMeta;
  nome_completo?: string;
  eta?: number;
  is_attivo?: boolean;
  is_admin?: boolean;
  id_gdo?: string;
}

/**
 * DTO per il login dell'utente
 */
export interface LoginUtenteDTO {
  email: string;
  password: string;
}

/**
 * DTO per la risposta del login
 */
export interface LoginResponseDTO {
  utente: UtenteResponseDTO;
  token: string;
  refresh_token?: string;
}

/**
 * DTO per il cambio password
 */
export interface ChangePasswordDTO {
  current_password: string;
  new_password: string;
  confirm_password: string;
}

/**
 * DTO per il reset password
 */
export interface ResetPasswordDTO {
  email: string;
}

/**
 * DTO per la conferma reset password
 */
export interface ConfirmResetPasswordDTO {
  token: string;
  new_password: string;
  confirm_password: string;
}

/**
 * DTO per i filtri di ricerca utenti
 */
export interface UtenteFiltersDTO {
  tipo?: TIPO_UTENTI;
  stato?: STATO_UTENTI;
  outsider?: boolean;
  search?: string;
  limit?: number;
  offset?: number;
  order_by?: 'nome' | 'cognome' | 'email' | 'createdat';
  order_direction?: 'ASC' | 'DESC';
}

/**
 * DTO per la risposta paginata degli utenti
 */
export interface UtentiPaginatedResponseDTO {
  utenti: UtenteResponseDTO[];
  total: number;
  page: number;
  limit: number;
  total_pages: number;
}

/**
 * DTO per le statistiche degli utenti
 */
export interface UtenteStatsDTO {
  total: number;
  utenti_attivi: number;
  utenti_inattivi: number;
  per_tipo: Record<TIPO_UTENTI, number>;
  per_stato: Record<STATO_UTENTI, number>;
  ultimi_registrati: UtenteResponseDTO[];
}

/**
 * DTO per la risposta paginata degli utenti con canali di interazione
 */
export interface UtentePaginatedResponseDTO {
  utenti: (UtenteResponseDTO & {
    canaliInterazione?: CanaliInterazioneResponseDTO[];
    ruoloGDO?: {
      id: string;
      ruolo: string;
    } | null;
    puntoVenditaCollegato?: {
      id: string;
      nome: string;
    } | null;
  })[];
  total: number;
  page: number;
  limit: number;
  total_pages: number;
}



export function toUtenteResponseDTO(utente: UtenteAttributes): UtenteResponseDTO {
  return {
    id: utente.id_utenti,
    outsider: utente.outsider_utenti,
    nome: utente.nome_utenti || '',
    cognome: utente.cognome_utenti || '',
    email: utente.email_utenti || '',
    datadinascita: utente.datadinascita_utenti,
    residenza: utente.residenza_utenti,
    tipo: utente.tipo_utenti,
    stato: utente.stato_utenti || STATO_UTENTI.ATTIVO,
    sesso: utente.sesso_utenti,
    telefono: utente.telefono_utenti,
    private_key: utente.privatekey_utenti,
    createdat: utente.createdat,
    updatedat: utente.updatedat || new Date(),
    meta: utente.meta_utenti,
    nome_completo: utente.nome_utenti && utente.cognome_utenti ? `${utente.nome_utenti} ${utente.cognome_utenti}` : undefined,
    eta: utente.datadinascita_utenti ? Math.floor((Date.now() - new Date(utente.datadinascita_utenti).getTime()) / (365.25 * 24 * 60 * 60 * 1000)) : undefined,
    is_attivo: utente.stato_utenti === STATO_UTENTI.ATTIVO,
    is_admin: utente.tipo_utenti === TIPO_UTENTI.SUPERADMIN
  }
}

export function toUtenteAttributes(utente: CreateUtenteDTO): UtenteAttributes {
  return {
    id_utenti: '', // Will be generated by database
    outsider_utenti: utente.outsider || false,
    nome_utenti: utente.nome,
    cognome_utenti: utente.cognome,
    email_utenti: utente.email,
    password_utenti: utente.password || '',
    tipo_utenti: utente.tipo,
    datadinascita_utenti: utente.datadinascita,
    residenza_utenti: utente.residenza,
    stato_utenti: utente.stato || STATO_UTENTI.ATTIVO,
    sesso_utenti: utente.sesso,
    telefono_utenti: utente.telefono,
    privatekey_utenti: utente.privatekey,
    meta_utenti: utente.meta,
    createdat: new Date(),
    updatedat: new Date()
  }
}

export function updateUtenteAttributes(utente: UpdateUtenteDTO): Partial<UtenteAttributes> {
  const attributes: Partial<UtenteAttributes> = {};

  if (utente.outsider !== undefined) attributes.outsider_utenti = utente.outsider;
  if (utente.nome !== undefined) attributes.nome_utenti = utente.nome;
  if (utente.cognome !== undefined) attributes.cognome_utenti = utente.cognome;
  if (utente.email !== undefined) attributes.email_utenti = utente.email;
  if (utente.password !== undefined) attributes.password_utenti = utente.password;
  if (utente.tipo !== undefined) attributes.tipo_utenti = utente.tipo;
  if (utente.datadinascita !== undefined) attributes.datadinascita_utenti = utente.datadinascita;
  if (utente.residenza !== undefined) attributes.residenza_utenti = utente.residenza;
  if (utente.stato !== undefined) attributes.stato_utenti = utente.stato;
  if (utente.sesso !== undefined) attributes.sesso_utenti = utente.sesso;
  if (utente.telefono !== undefined) attributes.telefono_utenti = utente.telefono;
  if (utente.privatekey !== undefined) attributes.privatekey_utenti = utente.privatekey;
  if (utente.meta !== undefined) attributes.meta_utenti = utente.meta;

  attributes.updatedat = new Date();

  return attributes;
}
