-- Schema unico del database di Istanta.
-- 
-- GENERATO per composizione da pg-ctx1.sql e pg-ctx2.sql (radice del
-- repository), tenendo SOLO le tabelle che i contesti EF mappano davvero con
-- ToTable: undici da edro21_dbContext (Models) e quattordici da
-- Edro21_DbContext2 (Models_2), per un totale di 25.
-- 
-- Cosa NON c'e', e perche':
-- 
--   - le quindici tabelle PascalCase residue del modello precedente (Promo,
--     PromoLavorazioni, AddestramentoExcel, MenaboPagine, Attivitum, ...): sono
--     nei file sorgente ma nessun ToTable punta a loro;
--   - promo_lavorazioni_records_register: il codice non la usa piu', e nei file
--     sorgente esisteva solo col vecchio nome PascalCase.
-- 
-- UNICA CORREZIONE applicata al DDL originale: in promo_importazioni la chiave
-- esterna riferiva "Attivitum" ("Id"), cioe' il nome dell'entita' e una colonna
-- PascalCase; qui riferisce "Attivita" (id), che e' la tabella davvero mappata
-- da ctx1 e la sua colonna reale.
-- 
-- Le tabelle sono ordinate perche' ogni genitore preceda i suoi figli, cosi' le
-- chiavi esterne in linea si risolvono.
-- 
-- RIGENERARE questo file se cambiano i ToTable dei contesti o i file sorgente.

-- Attivita  (da pg-ctx1.sql)
CREATE TABLE "Attivita" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_parent bigint NULL,
    id_utente smallint NULL,
    coda smallint NOT NULL,
    titolo character varying(250) NOT NULL,
    contract character varying(500) NOT NULL,
    data_inserimento timestamp without time zone NOT NULL,
    tipo smallint NOT NULL DEFAULT (((1))),
    tipo_processo smallint NOT NULL DEFAULT (((1))),
    stato smallint NOT NULL,
    progress smallint NOT NULL,
    stato_msg character varying(250) NULL,
    data_fine timestamp without time zone NULL,
    data_inizio timestamp without time zone NULL,
    priorita smallint NOT NULL,
    CONSTRAINT "PK_Attivita" PRIMARY KEY (id),
    CONSTRAINT "FK_Attivita_Attivita" FOREIGN KEY (id_parent) REFERENCES "Attivita" (id)
);
CREATE INDEX "IX_Attivita_id_parent" ON "Attivita" (id_parent);

-- AttivitaLogs  (da pg-ctx1.sql)
CREATE TABLE "AttivitaLogs" (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_attivita bigint NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    tipo smallint NOT NULL,
    note text NOT NULL,
    CONSTRAINT "PK_AttivitaLogs" PRIMARY KEY (id),
    CONSTRAINT "FK_AttivitaLogs_Attivita" FOREIGN KEY (id_attivita) REFERENCES "Attivita" (id)
);
CREATE INDEX "IX_AttivitaLogs_id_attivita" ON "AttivitaLogs" (id_attivita);

-- addestramento_excel  (da pg-ctx2.sql)
CREATE TABLE addestramento_excel (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    file_addestramento character varying(150) NOT NULL,
    titolo character varying(100) NULL,
    data_caricamento timestamp without time zone NOT NULL,
    "esportaSubito" boolean NOT NULL,
    "salvaSuDb" boolean NOT NULL,
    "externalCallPerImport" text NULL,
    "externalCallPerExport" text NULL,
    "externalCallPerExportPoP" text NULL,
    CONSTRAINT "PK_addestramento_excel" PRIMARY KEY (id)
);

-- schema_campi_excel  (da pg-ctx2.sql)
CREATE TABLE schema_campi_excel (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_addestramento integer NOT NULL,
    nome_colonna_originale character varying(70) NOT NULL,
    indice smallint NOT NULL,
    nome_colonna character varying(70) NULL,
    nome_visualizzato character varying(70) NULL,
    note character varying(500) NULL,
    tipo_dato smallint NULL,
    ruolo character varying(100) NULL,
    ordinamento smallint NULL DEFAULT (((0))),
    CONSTRAINT "PK_schema_campi_excel" PRIMARY KEY (id),
    CONSTRAINT "FK_schema_campi_excel_addestramento_excel" FOREIGN KEY (id_addestramento) REFERENCES addestramento_excel (id)
);
CREATE INDEX "IX_schema_campi_excel_id_addestramento" ON schema_campi_excel (id_addestramento);
COMMENT ON COLUMN schema_campi_excel.ordinamento IS '0 - none 1 - categoria(liv1) 2 - reparto (liv2) 3 - settore (liv 3) 4 - segmento (liv 4)';

-- addestramento_excel_relazioni  (da pg-ctx2.sql)
CREATE TABLE addestramento_excel_relazioni (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_campo bigint NOT NULL,
    nome_relazione character varying(50) NOT NULL,
    algoritmo text NULL,
    tipo_compilazione smallint NOT NULL DEFAULT (((1))),
    CONSTRAINT "PK_addestramento_excel_relazioni" PRIMARY KEY (id),
    CONSTRAINT "FK_addestramento_excel_relazioni_schema_campi_excel" FOREIGN KEY (id_campo) REFERENCES schema_campi_excel (id)
);
CREATE INDEX "IX_addestramento_excel_relazioni_id_campo" ON addestramento_excel_relazioni (id_campo);
COMMENT ON COLUMN addestramento_excel_relazioni.id_campo IS 'Rif al campo esteso, non trovato nell''excel';
COMMENT ON COLUMN addestramento_excel_relazioni.tipo_compilazione IS '1 - importazione inline 2 - importazione atend  3 - esportazione 4 - Manuale';

-- articoli  (da pg-ctx1.sql)
CREATE TABLE articoli (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    codice character varying(100) NOT NULL,
    descrizione1 character varying(4000) NOT NULL,
    descrizione2 character varying(4000) NOT NULL,
    descrizione3 character varying(4000) NOT NULL,
    descrizione4 character varying(4000) NOT NULL,
    peso numeric(18,3) NULL,
    um character varying(10) NULL,
    ultima_revisione timestamp without time zone NULL,
    stato_revisione smallint NOT NULL,
    nota_tecnica text NULL,
    reparto integer NULL,
    segmento character varying(20) NULL,
    ean character varying(30) NULL,
    data_inserimento timestamp without time zone NULL,
    data_modifica timestamp without time zone NULL,
    CONSTRAINT "PK_articoli" PRIMARY KEY (id)
);
COMMENT ON COLUMN articoli.stato_revisione IS '0 - non processato 1 - descrizione conad approvata 2 - descrizione conad bocciata 3 - obsoleto 4 - processato solo da edro';

-- articoli_descrizioni  (da pg-ctx1.sql)
CREATE TABLE articoli_descrizioni (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_articolo bigint NULL,
    codice_gruppo text NULL,
    area character varying(30) NULL,
    canale character varying(30) NULL,
    custom character varying(1000) NULL,
    descrizione_1 character varying(4000) NULL,
    descrizione_2 character varying(4000) NULL,
    descrizione_3 character varying(4000) NULL,
    descrizione_4 character varying(4000) NULL,
    descrizione_indd character varying(4000) NULL,
    extra text NULL,
    peso numeric(18,3) NULL,
    um text NULL,
    data_ultima_ricezione timestamp without time zone NOT NULL,
    approvata boolean NOT NULL,
    attiva boolean NOT NULL,
    firma_tracciato text NULL,
    meta text NULL,
    CONSTRAINT "PK_articoli_descrizioni" PRIMARY KEY (id),
    CONSTRAINT "FK_articoli_descrizioni_articoli" FOREIGN KEY (id_articolo) REFERENCES articoli (id)
);
CREATE INDEX "IX_articoli_descrizioni_id_articolo" ON articoli_descrizioni (id_articolo);

-- articoli_foto  (da pg-ctx1.sql)
CREATE TABLE articoli_foto (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_articolo bigint NOT NULL,
    area character varying(30) NULL,
    canale character varying(30) NULL,
    path_foto character varying(250) NOT NULL,
    nome_reale character varying(250) NOT NULL,
    guid_id character varying(50) NOT NULL,
    puntatore boolean NOT NULL,
    data_inserimento timestamp without time zone NOT NULL,
    stato_selezione smallint NULL DEFAULT (((1))),
    attiva boolean NOT NULL DEFAULT true,
    hash character varying(200) NULL,
    data_modifica timestamp without time zone NULL,
    tipo smallint NULL,
    CONSTRAINT "PK_articoli_foto" PRIMARY KEY (id),
    CONSTRAINT "FK_articoli_foto_articoli" FOREIGN KEY (id_articolo) REFERENCES articoli (id)
);
CREATE INDEX "IX_articoli_foto_id_articolo" ON articoli_foto (id_articolo);
COMMENT ON COLUMN articoli_foto.stato_selezione IS '0 - no selezionata 1 - primaria 2 - selezionata';

-- foto_escluse  (da pg-ctx1.sql)
CREATE TABLE foto_escluse (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "idArticolo" bigint NOT NULL,
    nome_reale character varying(250) NOT NULL,
    data_inserimento timestamp without time zone NOT NULL,
    "Filtro" text NULL,
    CONSTRAINT "PK_foto_escluse" PRIMARY KEY (id),
    CONSTRAINT "FK_foto_escluse_articoli" FOREIGN KEY ("idArticolo") REFERENCES articoli (id)
);
CREATE INDEX "IX_foto_escluse_idArticolo" ON foto_escluse ("idArticolo");

-- promo  (da pg-ctx2.sql)
CREATE TABLE promo (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    nome_promo character varying(100) NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    validita_dal timestamp without time zone NULL,
    validita_al timestamp without time zone NULL,
    data_scadenza timestamp without time zone NULL,
    stato smallint NOT NULL DEFAULT (((1))),
    "guidId" character varying(50) NULL,
    context text NULL,
    CONSTRAINT "PK_promo" PRIMARY KEY (id)
);
COMMENT ON COLUMN promo.stato IS '0-chiusa 1-aperta';

-- promo_importazioni  (da pg-ctx2.sql)
CREATE TABLE promo_importazioni (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_addestramento integer NOT NULL,
    id_promo integer NOT NULL,
    nome_file character varying(150) NOT NULL,
    tipo_materiale character varying(50) NULL,
    data_caricamento timestamp without time zone NOT NULL,
    "paramsRequest" text NULL,
    "guidId" character varying(50) NULL,
    id_attivita bigint NULL,
    CONSTRAINT "PK_promo_importazioni" PRIMARY KEY (id),
    CONSTRAINT "FK_promo_importazioni_addestramento_excel" FOREIGN KEY (id_addestramento) REFERENCES addestramento_excel (id),
    CONSTRAINT "FK_promo_importazioni_Attivita" FOREIGN KEY (id_attivita) REFERENCES "Attivita" (id),
    CONSTRAINT "FK_promo_importazioni_promo" FOREIGN KEY (id_promo) REFERENCES promo (id)
);
CREATE INDEX "IX_promo_importazioni_id_addestramento" ON promo_importazioni (id_addestramento);
CREATE INDEX "IX_promo_importazioni_id_attivita" ON promo_importazioni (id_attivita);
CREATE INDEX "IX_promo_importazioni_id_promo" ON promo_importazioni (id_promo);

-- promo_tracciati  (da pg-ctx2.sql)
CREATE TABLE promo_tracciati (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_importazione integer NOT NULL,
    id_promo integer NOT NULL,
    versione smallint NOT NULL,
    sigla character varying(50) NULL,
    "guidArea" character varying(50) NULL,
    "guidCanale" character varying(50) NULL,
    "guidPV" character varying(50) NULL,
    area text NULL,
    canale text NULL,
    ordine_lista text NULL,
    meta text NULL,
    context text NULL,
    CONSTRAINT "PK_promo_tracciati" PRIMARY KEY (id),
    CONSTRAINT "FK_promo_tracciati_promo" FOREIGN KEY (id_promo) REFERENCES promo (id),
    CONSTRAINT "FK_promo_tracciati_promo_importazioni" FOREIGN KEY (id_importazione) REFERENCES promo_importazioni (id)
);
CREATE INDEX "IX_promo_tracciati_id_importazione" ON promo_tracciati (id_importazione);
CREATE INDEX "IX_promo_tracciati_id_promo" ON promo_tracciati (id_promo);

-- menabo_pagine  (da pg-ctx2.sql)
CREATE TABLE menabo_pagine (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_tracciato integer NOT NULL,
    numero smallint NOT NULL,
    formato character varying(15) NULL,
    id_mastro smallint NOT NULL,
    CONSTRAINT "PK_menabo_pagine" PRIMARY KEY (id),
    CONSTRAINT "FK_menabo_pagine_promo_tracciati" FOREIGN KEY (id_tracciato) REFERENCES promo_tracciati (id)
);
CREATE INDEX "IX_menabo_pagine_id_tracciato" ON menabo_pagine (id_tracciato);

-- promo_tracciati_records  (da pg-ctx2.sql)
CREATE TABLE promo_tracciati_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_tracciato integer NOT NULL,
    versione smallint NOT NULL,
    indice_lettura integer NOT NULL,
    indice_esportazione integer NOT NULL DEFAULT (((-1))),
    label character varying(40) NULL,
    scatto character varying(500) NULL,
    codice character varying(100) NULL,
    codice_gruppo character varying(4000) NULL,
    dato text NULL,
    da_esportare boolean NULL,
    id_addestramento integer NULL,
    data_registrazione timestamp without time zone NULL,
    modalita_inserimento smallint NOT NULL,
    stato smallint NOT NULL,
    CONSTRAINT "PK_promo_tracciati_records" PRIMARY KEY (id),
    CONSTRAINT "FK_promo_importazioni_Attivita" FOREIGN KEY (id_addestramento) REFERENCES addestramento_excel (id),
    CONSTRAINT "FK_promo_tracciati_records_promo_tracciati" FOREIGN KEY (id_tracciato) REFERENCES promo_tracciati (id)
);
CREATE INDEX "IX_promo_tracciati_records_id_addestramento" ON promo_tracciati_records (id_addestramento);
CREATE INDEX "IX_promo_tracciati_records_id_tracciato" ON promo_tracciati_records (id_tracciato);

-- menabo_ref  (da pg-ctx2.sql)
CREATE TABLE menabo_ref (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_record bigint NULL,
    codice_gruppo character varying(2000) NULL,
    id_pagina bigint NOT NULL,
    indice smallint NOT NULL,
    selezione smallint NOT NULL,
    formato character varying(100) NULL,
    meccanica text NULL,
    CONSTRAINT "PK_menabo_ref" PRIMARY KEY (id),
    CONSTRAINT "FK_menabo_promo_tracciati_records" FOREIGN KEY (id_record) REFERENCES promo_tracciati_records (id),
    CONSTRAINT "FK_menabo_ref_menabo_pagine" FOREIGN KEY (id_pagina) REFERENCES menabo_pagine (id)
);
CREATE INDEX "IX_menabo_ref_id_pagina" ON menabo_ref (id_pagina);
CREATE INDEX "IX_menabo_ref_id_record" ON menabo_ref (id_record);

-- promo_lavorazioni  (da pg-ctx2.sql)
CREATE TABLE promo_lavorazioni (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    "guidId" text NULL,
    "guidPromo" text NULL,
    "guidCanale" text NULL,
    "guidArea" text NULL,
    "guidRaccoglitore" text NULL,
    "guidFormato" text NULL,
    id_autore smallint NOT NULL,
    register_date timestamp without time zone NOT NULL,
    meta text NULL,
    stato smallint NOT NULL,
    CONSTRAINT "PK_promo_lavorazioni" PRIMARY KEY (id)
);

-- promo_lavorazioni_records  (da pg-ctx2.sql)
CREATE TABLE promo_lavorazioni_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_lavorazione integer NOT NULL,
    id_record_tracciato bigint NOT NULL,
    codice text NULL,
    codice_gruppo character varying(4000) NULL,
    id_autore smallint NOT NULL,
    register_date timestamp without time zone NULL,
    indice smallint NOT NULL,
    pagina smallint NOT NULL,
    meta text NULL,
    CONSTRAINT "PK_promo_lavorazioni_records" PRIMARY KEY (id),
    CONSTRAINT "FK_promo_lavorazioni_records_promo_lavorazioni" FOREIGN KEY (id_lavorazione) REFERENCES promo_lavorazioni (id),
    CONSTRAINT "FK_promo_lavorazioni_records_promo_tracciati_records" FOREIGN KEY (id_record_tracciato) REFERENCES promo_tracciati_records (id)
);
CREATE INDEX "IX_promo_lavorazioni_records_id_lavorazione" ON promo_lavorazioni_records (id_lavorazione);
CREATE INDEX "IX_promo_lavorazioni_records_id_record_tracciato" ON promo_lavorazioni_records (id_record_tracciato);

-- registro_operazioni  (da pg-ctx1.sql)
CREATE TABLE registro_operazioni (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo_operazione smallint NOT NULL,
    codice_associato character varying(4000) NULL,
    "idTracciato" integer NULL,
    "idPromoLavorazione" integer NULL,
    "idPromoLavorazioniRecord" bigint NULL,
    area character varying(30) NULL,
    canale character varying(30) NULL,
    url text NULL,
    "formData" text NULL,
    data_registrazione timestamp without time zone NOT NULL,
    data_esecuzione timestamp without time zone NULL,
    data_elaborazione_propagazioni timestamp without time zone NULL,
    stato smallint NOT NULL,
    autore integer NOT NULL,
    esecutore integer NULL,
    CONSTRAINT "PK_registro_operazioni" PRIMARY KEY (id)
);

-- utenti  (da pg-ctx1.sql)
CREATE TABLE utenti (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    "nomeUtente" character varying(150) NOT NULL,
    nome character varying(150) NULL,
    cognome character varying(150) NULL,
    email character varying(150) NOT NULL,
    password character varying(50) NOT NULL,
    stato smallint NOT NULL,
    ruolo smallint NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    data_update timestamp without time zone NULL,
    "privateKey" character varying(50) NULL,
    ad_token character varying(50) NULL,
    scadenza_token_ad timestamp with time zone NULL,
    "policyGroups" character varying(150) NULL,
    CONSTRAINT "PK_utenti" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "IX_utenti_email" ON utenti (email);

-- registro_propagazioni  (da pg-ctx1.sql)
CREATE TABLE registro_propagazioni (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    "idRegistro" bigint NOT NULL,
    "idPromoLavorazioneRecord" bigint NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    data_elaborazione timestamp without time zone NULL,
    autore_elaborazione smallint NULL,
    priorita smallint NOT NULL,
    stato smallint NOT NULL,
    CONSTRAINT "PK_registro_propagazioni" PRIMARY KEY (id),
    CONSTRAINT "FK_registro_propagazioni_registro_operazioni" FOREIGN KEY ("idRegistro") REFERENCES registro_operazioni (id) ON DELETE CASCADE,
    CONSTRAINT "FK_registro_propagazioni_utenti" FOREIGN KEY (autore_elaborazione) REFERENCES utenti (id)
);
CREATE INDEX "IX_registro_propagazioni_autore_elaborazione" ON registro_propagazioni (autore_elaborazione);
CREATE INDEX "IX_registro_propagazioni_idRegistro" ON registro_propagazioni ("idRegistro");

-- schema_campi_excel_relazioni  (da pg-ctx2.sql)
CREATE TABLE schema_campi_excel_relazioni (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_relazione integer NOT NULL,
    id_campo bigint NOT NULL,
    condizione character varying(500) NULL,
    CONSTRAINT "PK_schema_campi_excel_relazioni" PRIMARY KEY (id),
    CONSTRAINT "FK_schema_campi_excel_relazioni_addestramento_excel_relazioni" FOREIGN KEY (id_relazione) REFERENCES addestramento_excel_relazioni (id),
    CONSTRAINT "FK_schema_campi_excel_relazioni_schema_campi_excel" FOREIGN KEY (id_campo) REFERENCES schema_campi_excel (id)
);
CREATE INDEX "IX_schema_campi_excel_relazioni_id_campo" ON schema_campi_excel_relazioni (id_campo);
CREATE INDEX "IX_schema_campi_excel_relazioni_id_relazione" ON schema_campi_excel_relazioni (id_relazione);
COMMENT ON COLUMN schema_campi_excel_relazioni.id_campo IS 'Rif al campo essitente sull''excel';

-- schema_custom  (da pg-ctx2.sql)
CREATE TABLE schema_custom (
    id smallint GENERATED BY DEFAULT AS IDENTITY,
    titolo character varying(60) NOT NULL,
    data_registrazione timestamp without time zone NOT NULL,
    CONSTRAINT "PK_schema_custom" PRIMARY KEY (id)
);

-- schema_custom_records  (da pg-ctx2.sql)
CREATE TABLE schema_custom_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    id_schema smallint NOT NULL,
    dato text NOT NULL,
    CONSTRAINT "PK_schema_custom_records" PRIMARY KEY (id),
    CONSTRAINT "FK_schema_custom_records_schema_custom" FOREIGN KEY (id_schema) REFERENCES schema_custom (id)
);
CREATE INDEX "IX_schema_custom_records_id_schema" ON schema_custom_records (id_schema);

-- settings  (da pg-ctx1.sql)
CREATE TABLE settings (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    codice character varying(80) NOT NULL,
    valore text NOT NULL,
    CONSTRAINT "PK_settings" PRIMARY KEY (id)
);

-- utenti_fico  (da pg-ctx1.sql)
CREATE TABLE utenti_fico (
    id integer GENERATED BY DEFAULT AS IDENTITY,
    id_utente smallint NULL,
    token character varying(100) NOT NULL,
    origin character varying(50) NOT NULL,
    username character varying(150) NOT NULL,
    tipo_utente smallint NOT NULL,
    user_data text NOT NULL,
    last_access timestamp without time zone NOT NULL,
    CONSTRAINT "PK_utenti_fico" PRIMARY KEY (id),
    CONSTRAINT "FK_utenti_fico_utenti" FOREIGN KEY (id_utente) REFERENCES utenti (id)
);
CREATE INDEX "IX_utenti_fico_id_utente" ON utenti_fico (id_utente);
