// <auto-generated />
using System;
using Istanta.Models_2;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Istanta.Migrations.Contesto2
{
    [DbContext(typeof(Edro21_DbContext2))]
    [Migration("20260930090250_Baseline")]
    partial class Baseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Istanta.Models.AttivitaLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("IdAttivita")
                        .HasColumnType("bigint");

                    b.Property<long>("IdAttivitaNavigationId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("Tipo")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("IdAttivitaNavigationId");

                    b.ToTable("AttivitaLog");
                });

            modelBuilder.Entity("Istanta.Models.Attivitum", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<byte>("Coda")
                        .HasColumnType("smallint");

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DataFine")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataInizio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataInserimento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("IdParent")
                        .HasColumnType("bigint");

                    b.Property<long?>("IdParentNavigationId")
                        .HasColumnType("bigint");

                    b.Property<short?>("IdUtente")
                        .HasColumnType("smallint");

                    b.Property<byte>("Priorita")
                        .HasColumnType("smallint");

                    b.Property<short>("Progress")
                        .HasColumnType("smallint");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint");

                    b.Property<string>("StatoMsg")
                        .HasColumnType("text");

                    b.Property<byte>("Tipo")
                        .HasColumnType("smallint");

                    b.Property<byte>("TipoProcesso")
                        .HasColumnType("smallint");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdParentNavigationId");

                    b.ToTable("Attivitum");
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_caricamento");

                    b.Property<string>("FileAddestramento")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("file_addestramento");

                    b.Property<string>("Titolo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("titolo");

                    b.Property<bool>("esportaSubito")
                        .HasColumnType("boolean")
                        .HasColumnName("esportaSubito");

                    b.Property<string>("externalCallPerExport")
                        .HasColumnType("text")
                        .HasColumnName("externalCallPerExport");

                    b.Property<string>("externalCallPerExportPoP")
                        .HasColumnType("text")
                        .HasColumnName("externalCallPerExportPoP");

                    b.Property<string>("externalCallPerImport")
                        .HasColumnType("text")
                        .HasColumnName("externalCallPerImport");

                    b.Property<bool>("salvaSuDb")
                        .HasColumnType("boolean")
                        .HasColumnName("salvaSuDb");

                    b.HasKey("Id");

                    b.ToTable("addestramento_excel", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcelRelazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Algoritmo")
                        .HasColumnType("text")
                        .HasColumnName("algoritmo");

                    b.Property<long>("IdCampo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_campo")
                        .HasComment("Rif al campo esteso, non trovato nell'excel");

                    b.Property<string>("NomeRelazione")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nome_relazione");

                    b.Property<byte>("TipoCompilazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_compilazione")
                        .HasDefaultValueSql("((1))")
                        .HasComment("1 - importazione inline 2 - importazione atend  3 - esportazione 4 - Manuale");

                    b.HasKey("Id");

                    b.HasIndex("IdCampo");

                    b.ToTable("addestramento_excel_relazioni", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboPagine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Formato")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("formato");

                    b.Property<short>("IdMastro")
                        .HasColumnType("smallint")
                        .HasColumnName("id_mastro");

                    b.Property<int>("IdTracciato")
                        .HasColumnType("integer")
                        .HasColumnName("id_tracciato");

                    b.Property<short>("Numero")
                        .HasColumnType("smallint")
                        .HasColumnName("numero");

                    b.HasKey("Id");

                    b.HasIndex("IdTracciato");

                    b.ToTable("menabo_pagine", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboRef", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CodiceGruppo")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("codice_gruppo");

                    b.Property<string>("Formato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("formato");

                    b.Property<long>("IdPagina")
                        .HasColumnType("bigint")
                        .HasColumnName("id_pagina");

                    b.Property<long?>("IdRecord")
                        .HasColumnType("bigint")
                        .HasColumnName("id_record");

                    b.Property<short>("Indice")
                        .HasColumnType("smallint")
                        .HasColumnName("indice");

                    b.Property<string>("Meccaniche")
                        .HasColumnType("text")
                        .HasColumnName("meccanica");

                    b.Property<byte>("Selezione")
                        .HasColumnType("smallint")
                        .HasColumnName("selezione");

                    b.HasKey("Id");

                    b.HasIndex("IdPagina");

                    b.HasIndex("IdRecord");

                    b.ToTable("menabo_ref", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.Promo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_registrazione");

                    b.Property<DateTime?>("DataScadenza")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_scadenza");

                    b.Property<string>("NomePromo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome_promo");

                    b.Property<byte>("Stato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("stato")
                        .HasDefaultValueSql("((1))")
                        .HasComment("0-chiusa 1-aperta");

                    b.Property<DateTime?>("ValiditaAl")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("validita_al");

                    b.Property<DateTime?>("ValiditaDal")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("validita_dal");

                    b.Property<string>("guidID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guidId");

                    b.HasKey("Id");

                    b.ToTable("promo", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.PromoImportazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCaricamento")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_caricamento");

                    b.Property<int>("IdAddestramento")
                        .HasColumnType("integer")
                        .HasColumnName("id_addestramento");

                    b.Property<long?>("IdAttivita")
                        .HasColumnType("bigint")
                        .HasColumnName("id_attivita");

                    b.Property<int>("IdPromo")
                        .HasColumnType("integer")
                        .HasColumnName("id_promo");

                    b.Property<string>("NomeFile")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nome_file");

                    b.Property<string>("ParamsRequest")
                        .HasColumnType("text")
                        .HasColumnName("paramsRequest");

                    b.Property<string>("TipoMateriale")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_materiale");

                    b.Property<string>("guidID")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guidId");

                    b.HasKey("Id");

                    b.HasIndex("IdAddestramento");

                    b.HasIndex("IdAttivita");

                    b.HasIndex("IdPromo");

                    b.ToTable("promo_importazioni", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GuidArea")
                        .HasColumnType("text")
                        .HasColumnName("guidArea");

                    b.Property<string>("GuidCanale")
                        .HasColumnType("text")
                        .HasColumnName("guidCanale");

                    b.Property<string>("GuidFormato")
                        .HasColumnType("text")
                        .HasColumnName("guidFormato");

                    b.Property<string>("GuidId")
                        .HasColumnType("text")
                        .HasColumnName("guidId");

                    b.Property<string>("GuidPromo")
                        .HasColumnType("text")
                        .HasColumnName("guidPromo");

                    b.Property<string>("GuidRaccoglitore")
                        .HasColumnType("text")
                        .HasColumnName("guidRaccoglitore");

                    b.Property<short>("IdAutore")
                        .HasColumnType("smallint")
                        .HasColumnName("id_autore");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<DateTime>("RegisterDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("register_date");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint")
                        .HasColumnName("stato");

                    b.HasKey("Id");

                    b.ToTable("promo_lavorazioni", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codice")
                        .HasColumnType("text")
                        .HasColumnName("codice");

                    b.Property<string>("CodiceGruppo")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("codice_gruppo");

                    b.Property<short>("IdAutore")
                        .HasColumnType("smallint")
                        .HasColumnName("id_autore");

                    b.Property<int>("IdLavorazione")
                        .HasColumnType("integer")
                        .HasColumnName("id_lavorazione");

                    b.Property<long>("IdRecordTracciato")
                        .HasColumnType("bigint")
                        .HasColumnName("id_record_tracciato");

                    b.Property<byte>("Indice")
                        .HasColumnType("smallint")
                        .HasColumnName("indice");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<byte>("Pagina")
                        .HasColumnType("smallint")
                        .HasColumnName("pagina");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("register_date");

                    b.HasKey("Id");

                    b.HasIndex("IdLavorazione");

                    b.HasIndex("IdRecordTracciato");

                    b.ToTable("promo_lavorazioni_records", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecordRegister", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<short>("IdAutore")
                        .HasColumnType("smallint");

                    b.Property<long>("IdLavorazioneRecord")
                        .HasColumnType("bigint");

                    b.Property<long>("IdPromoLavorazioniRecordNavigationId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("TipoAzione")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("IdPromoLavorazioniRecordNavigationId");

                    b.ToTable("PromoLavorazioniRecordRegister");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciati", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("text")
                        .HasColumnName("area");

                    b.Property<string>("Canale")
                        .HasColumnType("text")
                        .HasColumnName("canale");

                    b.Property<string>("Context")
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<int>("IdImportazione")
                        .HasColumnType("integer")
                        .HasColumnName("id_importazione");

                    b.Property<int>("IdPromo")
                        .HasColumnType("integer")
                        .HasColumnName("id_promo");

                    b.Property<string>("Meta")
                        .HasColumnType("text")
                        .HasColumnName("meta");

                    b.Property<string>("OrdineLista")
                        .HasColumnType("text")
                        .HasColumnName("ordine_lista");

                    b.Property<string>("Sigla")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("sigla");

                    b.Property<byte>("Versione")
                        .HasColumnType("smallint")
                        .HasColumnName("versione");

                    b.Property<string>("guidArea")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guidArea");

                    b.Property<string>("guidCanale")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guidCanale");

                    b.Property<string>("guidPV")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("guidPV");

                    b.HasKey("Id");

                    b.HasIndex("IdImportazione");

                    b.HasIndex("IdPromo");

                    b.ToTable("promo_tracciati", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciatiRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Codice")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("codice");

                    b.Property<string>("CodiceGruppo")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("codice_gruppo");

                    b.Property<bool?>("DaEsportare")
                        .HasColumnType("boolean")
                        .HasColumnName("da_esportare");

                    b.Property<DateTime?>("DataRegistrazione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_registrazione");

                    b.Property<string>("Dato")
                        .HasColumnType("text")
                        .HasColumnName("dato");

                    b.Property<int?>("IdAddestramento")
                        .HasColumnType("integer")
                        .HasColumnName("id_addestramento");

                    b.Property<int>("IdTracciato")
                        .HasColumnType("integer")
                        .HasColumnName("id_tracciato");

                    b.Property<int>("IndiceEsportazione")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("indice_esportazione")
                        .HasDefaultValueSql("((-1))");

                    b.Property<int>("IndiceLettura")
                        .HasColumnType("integer")
                        .HasColumnName("indice_lettura");

                    b.Property<string>("Label")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("label");

                    b.Property<byte>("ModalitaInserimento")
                        .HasColumnType("smallint")
                        .HasColumnName("modalita_inserimento");

                    b.Property<string>("Scatto")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("scatto");

                    b.Property<byte>("Stato")
                        .HasColumnType("smallint")
                        .HasColumnName("stato");

                    b.Property<byte>("Versione")
                        .HasColumnType("smallint")
                        .HasColumnName("versione");

                    b.HasKey("Id");

                    b.HasIndex("IdAddestramento");

                    b.HasIndex("IdTracciato");

                    b.ToTable("promo_tracciati_records", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("IdAddestramento")
                        .HasColumnType("integer")
                        .HasColumnName("id_addestramento");

                    b.Property<short>("Indice")
                        .HasColumnType("smallint")
                        .HasColumnName("indice");

                    b.Property<string>("NomeColonna")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("nome_colonna");

                    b.Property<string>("NomeColonnaOriginale")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("nome_colonna_originale");

                    b.Property<string>("NomeVisualizzato")
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("nome_visualizzato");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<byte?>("Ordinamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("ordinamento")
                        .HasDefaultValueSql("((0))")
                        .HasComment("0 - none 1 - categoria(liv1) 2 - reparto (liv2) 3 - settore (liv 3) 4 - segmento (liv 4)");

                    b.Property<string>("Ruolo")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ruolo");

                    b.Property<byte?>("TipoDato")
                        .HasColumnType("smallint")
                        .HasColumnName("tipo_dato");

                    b.HasKey("Id");

                    b.HasIndex("IdAddestramento");

                    b.ToTable("schema_campi_excel", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcelRelazioni", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Condizione")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("condizione");

                    b.Property<long>("IdCampo")
                        .HasColumnType("bigint")
                        .HasColumnName("id_campo")
                        .HasComment("Rif al campo essitente sull'excel");

                    b.Property<int>("IdRelazione")
                        .HasColumnType("integer")
                        .HasColumnName("id_relazione");

                    b.HasKey("Id");

                    b.HasIndex("IdCampo");

                    b.HasIndex("IdRelazione");

                    b.ToTable("schema_campi_excel_relazioni", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCustom", b =>
                {
                    b.Property<short>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Id"));

                    b.Property<DateTime>("DataRegistrazione")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_registrazione");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("titolo");

                    b.HasKey("Id");

                    b.ToTable("schema_custom", (string)null);
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCustomRecord", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Dato")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dato");

                    b.Property<short>("IdSchema")
                        .HasColumnType("smallint")
                        .HasColumnName("id_schema");

                    b.HasKey("Id");

                    b.HasIndex("IdSchema");

                    b.ToTable("schema_custom_records", (string)null);
                });

            modelBuilder.Entity("Istanta.Models.AttivitaLog", b =>
                {
                    b.HasOne("Istanta.Models.Attivitum", "IdAttivitaNavigation")
                        .WithMany("AttivitaLogs")
                        .HasForeignKey("IdAttivitaNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdAttivitaNavigation");
                });

            modelBuilder.Entity("Istanta.Models.Attivitum", b =>
                {
                    b.HasOne("Istanta.Models.Attivitum", "IdParentNavigation")
                        .WithMany("SubAttivita")
                        .HasForeignKey("IdParentNavigationId");

                    b.Navigation("IdParentNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcelRelazioni", b =>
                {
                    b.HasOne("Istanta.Models_2.SchemaCampiExcel", "IdCampoNavigation")
                        .WithMany("AddestramentoExcelRelazionis")
                        .HasForeignKey("IdCampo")
                        .IsRequired()
                        .HasConstraintName("FK_addestramento_excel_relazioni_schema_campi_excel");

                    b.Navigation("IdCampoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboPagine", b =>
                {
                    b.HasOne("Istanta.Models_2.PromoTracciati", "IdTracciatoNavigation")
                        .WithMany("MenaboPagines")
                        .HasForeignKey("IdTracciato")
                        .IsRequired()
                        .HasConstraintName("FK_menabo_pagine_promo_tracciati");

                    b.Navigation("IdTracciatoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboRef", b =>
                {
                    b.HasOne("Istanta.Models_2.MenaboPagine", "IdPaginaNavigation")
                        .WithMany("MenaboRefs")
                        .HasForeignKey("IdPagina")
                        .IsRequired()
                        .HasConstraintName("FK_menabo_ref_menabo_pagine");

                    b.HasOne("Istanta.Models_2.PromoTracciatiRecord", "IdRecordNavigation")
                        .WithMany("MenaboRefs")
                        .HasForeignKey("IdRecord")
                        .HasConstraintName("FK_menabo_promo_tracciati_records");

                    b.Navigation("IdPaginaNavigation");

                    b.Navigation("IdRecordNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoImportazioni", b =>
                {
                    b.HasOne("Istanta.Models_2.AddestramentoExcel", "IdAddestramentoNavigation")
                        .WithMany("PromoImportazionis")
                        .HasForeignKey("IdAddestramento")
                        .IsRequired()
                        .HasConstraintName("FK_promo_importazioni_addestramento_excel");

                    b.HasOne("Istanta.Models.Attivitum", "IdAttivitaNavigation")
                        .WithMany("PromoImportazionis")
                        .HasForeignKey("IdAttivita")
                        .HasConstraintName("FK_promo_importazioni_Attivita");

                    b.HasOne("Istanta.Models_2.Promo", "IdPromoNavigation")
                        .WithMany("PromoImportazionis")
                        .HasForeignKey("IdPromo")
                        .IsRequired()
                        .HasConstraintName("FK_promo_importazioni_promo");

                    b.Navigation("IdAddestramentoNavigation");

                    b.Navigation("IdAttivitaNavigation");

                    b.Navigation("IdPromoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecord", b =>
                {
                    b.HasOne("Istanta.Models_2.PromoLavorazioni", "IdPromoLavorazioniNavigation")
                        .WithMany("PromoLavorazioniRecords")
                        .HasForeignKey("IdLavorazione")
                        .IsRequired()
                        .HasConstraintName("FK_promo_lavorazioni_records_promo_lavorazioni");

                    b.HasOne("Istanta.Models_2.PromoTracciatiRecord", "IdPromoTracciatiRecordNavigation")
                        .WithMany("PromoLavorazioniRecords")
                        .HasForeignKey("IdRecordTracciato")
                        .IsRequired()
                        .HasConstraintName("FK_promo_lavorazioni_records_promo_tracciati_records");

                    b.Navigation("IdPromoLavorazioniNavigation");

                    b.Navigation("IdPromoTracciatiRecordNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecordRegister", b =>
                {
                    b.HasOne("Istanta.Models_2.PromoLavorazioniRecord", "IdPromoLavorazioniRecordNavigation")
                        .WithMany("PromoLavorazioniRecordRegisters")
                        .HasForeignKey("IdPromoLavorazioniRecordNavigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdPromoLavorazioniRecordNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciati", b =>
                {
                    b.HasOne("Istanta.Models_2.PromoImportazioni", "IdImportazioneNavigation")
                        .WithMany("PromoTracciatis")
                        .HasForeignKey("IdImportazione")
                        .IsRequired()
                        .HasConstraintName("FK_promo_tracciati_promo_importazioni");

                    b.HasOne("Istanta.Models_2.Promo", "IdPromoNavigation")
                        .WithMany("PromoTracciatis")
                        .HasForeignKey("IdPromo")
                        .IsRequired()
                        .HasConstraintName("FK_promo_tracciati_promo");

                    b.Navigation("IdImportazioneNavigation");

                    b.Navigation("IdPromoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciatiRecord", b =>
                {
                    b.HasOne("Istanta.Models_2.AddestramentoExcel", "IdAddestramentoNavigation")
                        .WithMany("PromoTracciatiRecords")
                        .HasForeignKey("IdAddestramento")
                        .HasConstraintName("FK_promo_importazioni_Attivita");

                    b.HasOne("Istanta.Models_2.PromoTracciati", "IdTracciatoNavigation")
                        .WithMany("PromoTracciatiRecords")
                        .HasForeignKey("IdTracciato")
                        .IsRequired()
                        .HasConstraintName("FK_promo_tracciati_records_promo_tracciati");

                    b.Navigation("IdAddestramentoNavigation");

                    b.Navigation("IdTracciatoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcel", b =>
                {
                    b.HasOne("Istanta.Models_2.AddestramentoExcel", "IdAddestramentoNavigation")
                        .WithMany("SchemaCampiExcels")
                        .HasForeignKey("IdAddestramento")
                        .IsRequired()
                        .HasConstraintName("FK_schema_campi_excel_addestramento_excel");

                    b.Navigation("IdAddestramentoNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcelRelazioni", b =>
                {
                    b.HasOne("Istanta.Models_2.SchemaCampiExcel", "IdCampoNavigation")
                        .WithMany("SchemaCampiExcelRelazionis")
                        .HasForeignKey("IdCampo")
                        .IsRequired()
                        .HasConstraintName("FK_schema_campi_excel_relazioni_schema_campi_excel");

                    b.HasOne("Istanta.Models_2.AddestramentoExcelRelazioni", "IdRelazioneNavigation")
                        .WithMany("SchemaCampiExcelRelazionis")
                        .HasForeignKey("IdRelazione")
                        .IsRequired()
                        .HasConstraintName("FK_schema_campi_excel_relazioni_addestramento_excel_relazioni");

                    b.Navigation("IdCampoNavigation");

                    b.Navigation("IdRelazioneNavigation");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCustomRecord", b =>
                {
                    b.HasOne("Istanta.Models_2.SchemaCustom", "IdSchemaNavigation")
                        .WithMany("SchemaCustomRecords")
                        .HasForeignKey("IdSchema")
                        .IsRequired()
                        .HasConstraintName("FK_schema_custom_records_schema_custom");

                    b.Navigation("IdSchemaNavigation");
                });

            modelBuilder.Entity("Istanta.Models.Attivitum", b =>
                {
                    b.Navigation("AttivitaLogs");

                    b.Navigation("PromoImportazionis");

                    b.Navigation("SubAttivita");
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcel", b =>
                {
                    b.Navigation("PromoImportazionis");

                    b.Navigation("PromoTracciatiRecords");

                    b.Navigation("SchemaCampiExcels");
                });

            modelBuilder.Entity("Istanta.Models_2.AddestramentoExcelRelazioni", b =>
                {
                    b.Navigation("SchemaCampiExcelRelazionis");
                });

            modelBuilder.Entity("Istanta.Models_2.MenaboPagine", b =>
                {
                    b.Navigation("MenaboRefs");
                });

            modelBuilder.Entity("Istanta.Models_2.Promo", b =>
                {
                    b.Navigation("PromoImportazionis");

                    b.Navigation("PromoTracciatis");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoImportazioni", b =>
                {
                    b.Navigation("PromoTracciatis");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioni", b =>
                {
                    b.Navigation("PromoLavorazioniRecords");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoLavorazioniRecord", b =>
                {
                    b.Navigation("PromoLavorazioniRecordRegisters");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciati", b =>
                {
                    b.Navigation("MenaboPagines");

                    b.Navigation("PromoTracciatiRecords");
                });

            modelBuilder.Entity("Istanta.Models_2.PromoTracciatiRecord", b =>
                {
                    b.Navigation("MenaboRefs");

                    b.Navigation("PromoLavorazioniRecords");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCampiExcel", b =>
                {
                    b.Navigation("AddestramentoExcelRelazionis");

                    b.Navigation("SchemaCampiExcelRelazionis");
                });

            modelBuilder.Entity("Istanta.Models_2.SchemaCustom", b =>
                {
                    b.Navigation("SchemaCustomRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
