//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Dropbox/Progetti/Istanta2/Antlr/Expression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
//[System.CLSCompliant(false)]
public partial class ExpressionParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, REL_OP=5, ID=6, NMIXSTRING=7, INT=8, DECIMAL=9, 
		WS=10;
	public const int
		RULE_expr = 0, RULE_comparison = 1;
	public static readonly string[] ruleNames = {
		"expr", "comparison"
	};

	private static readonly string[] _LiteralNames = {
		null, "'&&'", "'||'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "REL_OP", "ID", "NMIXSTRING", "INT", "DECIMAL", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Expression.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ExpressionParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public ExpressionParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public ExpressionParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ExprContext : ParserRuleContext {
		public ExprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expr; } }
	 
		public ExprContext() { }
		public virtual void CopyFrom(ExprContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class ComparisonExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ComparisonContext comparison() {
			return GetRuleContext<ComparisonContext>(0);
		}
		public ComparisonExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExpressionVisitor<TResult> typedVisitor = visitor as IExpressionVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitComparisonExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class ParenExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr() {
			return GetRuleContext<ExprContext>(0);
		}
		public ParenExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExpressionVisitor<TResult> typedVisitor = visitor as IExpressionVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParenExpr(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class LogicalExprContext : ExprContext {
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext[] expr() {
			return GetRuleContexts<ExprContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ExprContext expr(int i) {
			return GetRuleContext<ExprContext>(i);
		}
		public LogicalExprContext(ExprContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExpressionVisitor<TResult> typedVisitor = visitor as IExpressionVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLogicalExpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExprContext expr() {
		return expr(0);
	}

	private ExprContext expr(int _p) {
		ParserRuleContext _parentctx = Context;
		int _parentState = State;
		ExprContext _localctx = new ExprContext(Context, _parentState);
		ExprContext _prevctx = _localctx;
		int _startState = 0;
		EnterRecursionRule(_localctx, 0, RULE_expr, _p);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 10;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case ID:
			case INT:
				{
				_localctx = new ComparisonExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;

				State = 5;
				comparison();
				}
				break;
			case T__2:
				{
				_localctx = new ParenExprContext(_localctx);
				Context = _localctx;
				_prevctx = _localctx;
				State = 6;
				Match(T__2);
				State = 7;
				expr(0);
				State = 8;
				Match(T__3);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			Context.Stop = TokenStream.LT(-1);
			State = 17;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					if ( ParseListeners!=null )
						TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new LogicalExprContext(new ExprContext(_parentctx, _parentState));
					PushNewRecursionContext(_localctx, _startState, RULE_expr);
					State = 12;
					if (!(Precpred(Context, 3))) throw new FailedPredicateException(this, "Precpred(Context, 3)");
					State = 13;
					_la = TokenStream.LA(1);
					if ( !(_la==T__0 || _la==T__1) ) {
					ErrorHandler.RecoverInline(this);
					}
					else {
						ErrorHandler.ReportMatch(this);
					    Consume();
					}
					State = 14;
					expr(4);
					}
					} 
				}
				State = 19;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,1,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class ComparisonContext : ParserRuleContext {
		public ComparisonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_comparison; } }
	 
		public ComparisonContext() { }
		public virtual void CopyFrom(ComparisonContext context) {
			base.CopyFrom(context);
		}
	}
	public partial class IntIdComparisonContext : ComparisonContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(ExpressionParser.INT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REL_OP() { return GetToken(ExpressionParser.REL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ExpressionParser.ID, 0); }
		public IntIdComparisonContext(ComparisonContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExpressionVisitor<TResult> typedVisitor = visitor as IExpressionVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntIdComparison(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IntComparisonContext : ComparisonContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] INT() { return GetTokens(ExpressionParser.INT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT(int i) {
			return GetToken(ExpressionParser.INT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REL_OP() { return GetToken(ExpressionParser.REL_OP, 0); }
		public IntComparisonContext(ComparisonContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExpressionVisitor<TResult> typedVisitor = visitor as IExpressionVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIntComparison(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdIntComparisonContext : ComparisonContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ExpressionParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REL_OP() { return GetToken(ExpressionParser.REL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INT() { return GetToken(ExpressionParser.INT, 0); }
		public IdIntComparisonContext(ComparisonContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExpressionVisitor<TResult> typedVisitor = visitor as IExpressionVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdIntComparison(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdComparisonContext : ComparisonContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] ID() { return GetTokens(ExpressionParser.ID); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID(int i) {
			return GetToken(ExpressionParser.ID, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REL_OP() { return GetToken(ExpressionParser.REL_OP, 0); }
		public IdComparisonContext(ComparisonContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExpressionVisitor<TResult> typedVisitor = visitor as IExpressionVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdComparison(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdDecimalComparisonContext : ComparisonContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ExpressionParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REL_OP() { return GetToken(ExpressionParser.REL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DECIMAL() { return GetToken(ExpressionParser.DECIMAL, 0); }
		public IdDecimalComparisonContext(ComparisonContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExpressionVisitor<TResult> typedVisitor = visitor as IExpressionVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdDecimalComparison(this);
			else return visitor.VisitChildren(this);
		}
	}
	public partial class IdNumMixStringComparisonContext : ComparisonContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(ExpressionParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode REL_OP() { return GetToken(ExpressionParser.REL_OP, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode NMIXSTRING() { return GetToken(ExpressionParser.NMIXSTRING, 0); }
		public IdNumMixStringComparisonContext(ComparisonContext context) { CopyFrom(context); }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IExpressionVisitor<TResult> typedVisitor = visitor as IExpressionVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdNumMixStringComparison(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ComparisonContext comparison() {
		ComparisonContext _localctx = new ComparisonContext(Context, State);
		EnterRule(_localctx, 2, RULE_comparison);
		try {
			State = 38;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				_localctx = new IntComparisonContext(_localctx);
				EnterOuterAlt(_localctx, 1);
				{
				State = 20;
				Match(INT);
				State = 21;
				Match(REL_OP);
				State = 22;
				Match(INT);
				}
				break;
			case 2:
				_localctx = new IdNumMixStringComparisonContext(_localctx);
				EnterOuterAlt(_localctx, 2);
				{
				State = 23;
				Match(ID);
				State = 24;
				Match(REL_OP);
				State = 25;
				Match(NMIXSTRING);
				}
				break;
			case 3:
				_localctx = new IdIntComparisonContext(_localctx);
				EnterOuterAlt(_localctx, 3);
				{
				State = 26;
				Match(ID);
				State = 27;
				Match(REL_OP);
				State = 28;
				Match(INT);
				}
				break;
			case 4:
				_localctx = new IntIdComparisonContext(_localctx);
				EnterOuterAlt(_localctx, 4);
				{
				State = 29;
				Match(INT);
				State = 30;
				Match(REL_OP);
				State = 31;
				Match(ID);
				}
				break;
			case 5:
				_localctx = new IdComparisonContext(_localctx);
				EnterOuterAlt(_localctx, 5);
				{
				State = 32;
				Match(ID);
				State = 33;
				Match(REL_OP);
				State = 34;
				Match(ID);
				}
				break;
			case 6:
				_localctx = new IdDecimalComparisonContext(_localctx);
				EnterOuterAlt(_localctx, 6);
				{
				State = 35;
				Match(ID);
				State = 36;
				Match(REL_OP);
				State = 37;
				Match(DECIMAL);
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 0: return expr_sempred((ExprContext)_localctx, predIndex);
		}
		return true;
	}
	private bool expr_sempred(ExprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(Context, 3);
		}
		return true;
	}

	private static int[] _serializedATN = {
		4,1,10,41,2,0,7,0,2,1,7,1,1,0,1,0,1,0,1,0,1,0,1,0,3,0,11,8,0,1,0,1,0,1,
		0,5,0,16,8,0,10,0,12,0,19,9,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,
		1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,39,8,1,1,1,0,1,0,2,0,2,0,1,1,0,1,2,
		45,0,10,1,0,0,0,2,38,1,0,0,0,4,5,6,0,-1,0,5,11,3,2,1,0,6,7,5,3,0,0,7,8,
		3,0,0,0,8,9,5,4,0,0,9,11,1,0,0,0,10,4,1,0,0,0,10,6,1,0,0,0,11,17,1,0,0,
		0,12,13,10,3,0,0,13,14,7,0,0,0,14,16,3,0,0,4,15,12,1,0,0,0,16,19,1,0,0,
		0,17,15,1,0,0,0,17,18,1,0,0,0,18,1,1,0,0,0,19,17,1,0,0,0,20,21,5,8,0,0,
		21,22,5,5,0,0,22,39,5,8,0,0,23,24,5,6,0,0,24,25,5,5,0,0,25,39,5,7,0,0,
		26,27,5,6,0,0,27,28,5,5,0,0,28,39,5,8,0,0,29,30,5,8,0,0,30,31,5,5,0,0,
		31,39,5,6,0,0,32,33,5,6,0,0,33,34,5,5,0,0,34,39,5,6,0,0,35,36,5,6,0,0,
		36,37,5,5,0,0,37,39,5,9,0,0,38,20,1,0,0,0,38,23,1,0,0,0,38,26,1,0,0,0,
		38,29,1,0,0,0,38,32,1,0,0,0,38,35,1,0,0,0,39,3,1,0,0,0,3,10,17,38
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
