//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Dropbox/Progetti/Istanta2/Antlr/Expression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
//[System.CLSCompliant(false)]
public partial class ExpressionLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, REL_OP=5, ID=6, NMIXSTRING=7, INT=8, DECIMAL=9, 
		WS=10;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "REL_OP", "ID", "NMIXSTRING", "INT", "DECIMAL", 
		"WS"
	};


	public ExpressionLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public ExpressionLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'&&'", "'||'", "'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "REL_OP", "ID", "NMIXSTRING", "INT", "DECIMAL", 
		"WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Expression.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static ExpressionLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,10,91,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,
		2,7,7,7,2,8,7,8,2,9,7,9,1,0,1,0,1,0,1,1,1,1,1,1,1,2,1,2,1,3,1,3,1,4,1,
		4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,1,4,
		1,4,3,4,52,8,4,1,5,4,5,55,8,5,11,5,12,5,56,1,6,4,6,60,8,6,11,6,12,6,61,
		1,6,4,6,65,8,6,11,6,12,6,66,1,7,4,7,70,8,7,11,7,12,7,71,1,8,4,8,75,8,8,
		11,8,12,8,76,1,8,1,8,4,8,81,8,8,11,8,12,8,82,1,9,4,9,86,8,9,11,9,12,9,
		87,1,9,1,9,0,0,10,1,1,3,2,5,3,7,4,9,5,11,6,13,7,15,8,17,9,19,10,1,0,4,
		2,0,60,60,62,62,3,0,65,90,95,95,97,122,1,0,48,57,3,0,9,10,13,13,32,32,
		103,0,1,1,0,0,0,0,3,1,0,0,0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,
		0,0,0,0,13,1,0,0,0,0,15,1,0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,1,21,1,0,0,0,
		3,24,1,0,0,0,5,27,1,0,0,0,7,29,1,0,0,0,9,51,1,0,0,0,11,54,1,0,0,0,13,59,
		1,0,0,0,15,69,1,0,0,0,17,74,1,0,0,0,19,85,1,0,0,0,21,22,5,38,0,0,22,23,
		5,38,0,0,23,2,1,0,0,0,24,25,5,124,0,0,25,26,5,124,0,0,26,4,1,0,0,0,27,
		28,5,40,0,0,28,6,1,0,0,0,29,30,5,41,0,0,30,8,1,0,0,0,31,52,7,0,0,0,32,
		33,5,62,0,0,33,52,5,61,0,0,34,35,5,60,0,0,35,52,5,61,0,0,36,37,5,61,0,
		0,37,52,5,61,0,0,38,39,5,33,0,0,39,52,5,61,0,0,40,41,5,36,0,0,41,42,5,
		73,0,0,42,43,5,78,0,0,43,52,5,36,0,0,44,45,5,36,0,0,45,46,5,78,0,0,46,
		47,5,79,0,0,47,48,5,84,0,0,48,49,5,73,0,0,49,50,5,78,0,0,50,52,5,36,0,
		0,51,31,1,0,0,0,51,32,1,0,0,0,51,34,1,0,0,0,51,36,1,0,0,0,51,38,1,0,0,
		0,51,40,1,0,0,0,51,44,1,0,0,0,52,10,1,0,0,0,53,55,7,1,0,0,54,53,1,0,0,
		0,55,56,1,0,0,0,56,54,1,0,0,0,56,57,1,0,0,0,57,12,1,0,0,0,58,60,7,2,0,
		0,59,58,1,0,0,0,60,61,1,0,0,0,61,59,1,0,0,0,61,62,1,0,0,0,62,64,1,0,0,
		0,63,65,7,1,0,0,64,63,1,0,0,0,65,66,1,0,0,0,66,64,1,0,0,0,66,67,1,0,0,
		0,67,14,1,0,0,0,68,70,7,2,0,0,69,68,1,0,0,0,70,71,1,0,0,0,71,69,1,0,0,
		0,71,72,1,0,0,0,72,16,1,0,0,0,73,75,7,2,0,0,74,73,1,0,0,0,75,76,1,0,0,
		0,76,74,1,0,0,0,76,77,1,0,0,0,77,78,1,0,0,0,78,80,5,46,0,0,79,81,7,2,0,
		0,80,79,1,0,0,0,81,82,1,0,0,0,82,80,1,0,0,0,82,83,1,0,0,0,83,18,1,0,0,
		0,84,86,7,3,0,0,85,84,1,0,0,0,86,87,1,0,0,0,87,85,1,0,0,0,87,88,1,0,0,
		0,88,89,1,0,0,0,89,90,6,9,0,0,90,20,1,0,0,0,9,0,51,56,61,66,71,76,82,87,
		1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
