//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from E:/Dropbox/Progetti/Istanta2/Antlr/Expression.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ExpressionParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
//[System.CLSCompliant(false)]
public interface IExpressionVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by the <c>ComparisonExpr</c>
	/// labeled alternative in <see cref="ExpressionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComparisonExpr([NotNull] ExpressionParser.ComparisonExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="ExpressionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] ExpressionParser.ParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogicalExpr</c>
	/// labeled alternative in <see cref="ExpressionParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogicalExpr([NotNull] ExpressionParser.LogicalExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntComparison</c>
	/// labeled alternative in <see cref="ExpressionParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntComparison([NotNull] ExpressionParser.IntComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdNumMixStringComparison</c>
	/// labeled alternative in <see cref="ExpressionParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdNumMixStringComparison([NotNull] ExpressionParser.IdNumMixStringComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdIntComparison</c>
	/// labeled alternative in <see cref="ExpressionParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdIntComparison([NotNull] ExpressionParser.IdIntComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntIdComparison</c>
	/// labeled alternative in <see cref="ExpressionParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntIdComparison([NotNull] ExpressionParser.IntIdComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdComparison</c>
	/// labeled alternative in <see cref="ExpressionParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdComparison([NotNull] ExpressionParser.IdComparisonContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdDecimalComparison</c>
	/// labeled alternative in <see cref="ExpressionParser.comparison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdDecimalComparison([NotNull] ExpressionParser.IdDecimalComparisonContext context);
}
