// ─── Schema Momenti ───────────────────────────────────────────────────────────
export enum TIPO_SCHEMA {
  BUSINESS = 'BUSINESS',
  AGENZIA  = 'AGENZIA',
}

export enum ERRORS {
  GENERIC_SERVER_ERROR = "GENERIC_SERVER_ERROR",
  INVALID_REQUEST = "INVALID_REQUEST",
  INVALID_USER = "INVALID_USER",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_EMAIL = "INVALID_EMAIL",
  BAD_REQUEST = "BAD_REQUEST",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  NOT_FOUND = "NOT_FOUND",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SESSION_EXPIRED = "SESSION_EXPIRED",
  XML_PARSE_ERROR = "XML_PARSE_ERROR",
  PATH_ALREADY_EXISTS = "PATH_ALREADY_EXISTS",
  UNVERIFIED_USER = "UNVERIFIED USER",
}

export enum HttpStatusCode {
  // Informational responses (100–199)
  CONTINUE = 100,
  SWITCHING_PROTOCOLS = 101,
  PROCESSING = 102, // WebDAV
  EARLY_HINT = 103, // RFC 8297

  // Successful responses (200–299)
  OK = 200,
  CREATED = 201,
  ACCEPTED = 202,
  NON_AUTHORITATIVE_INFORMATION = 203,
  NO_CONTENT = 204,
  RESET_CONTENT = 205,
  PARTIAL_CONTENT = 206,
  MULTI_STATUS = 207, // WebDAV
  ALREADY_REPORTED = 208, // WebDAV
  IM_USED = 226, // HTTP Delta encoding

  // Redirection messages (300–399)
  MULTIPLE_CHOICES = 300,
  MOVED_PERMANENTLY = 301,
  FOUND = 302,
  SEE_OTHER = 303,
  NOT_MODIFIED = 304,
  USE_PROXY = 305,
  TEMPORARY_REDIRECT = 307,
  PERMANENT_REDIRECT = 308,

  // Client error responses (400–499)
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  PAYMENT_REQUIRED = 402,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  NOT_ACCEPTABLE = 406,
  PROXY_AUTHENTICATION_REQUIRED = 407,
  REQUEST_TIMEOUT = 408,
  CONFLICT = 409,
  GONE = 410,
  LENGTH_REQUIRED = 411,
  PRECONDITION_FAILED = 412,
  PAYLOAD_TOO_LARGE = 413,
  URI_TOO_LONG = 414,
  UNSUPPORTED_MEDIA_TYPE = 415,
  RANGE_NOT_SATISFIABLE = 416,
  EXPECTATION_FAILED = 417,
  I_AM_A_TEAPOT = 418, // RFC 2324
  MISDIRECTED_REQUEST = 421,
  UNPROCESSABLE_ENTITY = 422, // WebDAV
  LOCKED = 423, // WebDAV
  FAILED_DEPENDENCY = 424, // WebDAV
  TOO_EARLY = 425,
  UPGRADE_REQUIRED = 426,
  PRECONDITION_REQUIRED = 428,
  TOO_MANY_REQUESTS = 429,
  REQUEST_HEADER_FIELDS_TOO_LARGE = 431,
  UNAVAILABLE_FOR_LEGAL_REASONS = 451,

  // Server error responses (500–599)
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
  HTTP_VERSION_NOT_SUPPORTED = 505,
  VARIANT_ALSO_NEGOTIATES = 506,
  INSUFFICIENT_STORAGE = 507, // WebDAV
  LOOP_DETECTED = 508, // WebDAV
  NOT_EXTENDED = 510,
  NETWORK_AUTHENTICATION_REQUIRED = 511,
  NETWORK_CONNECT_TIMEOUT_ERROR = 599,
}

export enum FICO_ORIGIN {
  FP = 'FP',
  IS = 'IS',
  CO = 'CO',
  OL = 'OL',
}

export enum STATO_COMBINAZIONI {
  ATTIVO = "ATTIVO",
  DISATTIVO = "DISATTIVO",
}

// export enum STATO_PROMO {
//   PUBBLICATA = "PUBBLICATA",
//   IN_REVISIONE = "IN_REVISIONE",
//   IN_LAVORAZIONE = "IN_LAVORAZIONE",
//   ELIMINATA = "ELIMINATA",
// }
export enum STATO_PROMO {
  PIANIFICATA = "PIANIFICATA",
  IN_LAVORAZIONE = "IN_LAVORAZIONE",
  IN_SCADENZA = "IN_SCADENZA",
  IN_ATTESA_DI_VALIDITA = "IN_ATTESA_DI_VALIDITA",
  IN_RITARDO = "IN_RITARDO",
  VALIDA = "VALIDA",
  VALIDA_CON_ERRORI = "VALIDA_CON_ERRORI",
  ARCHIVIATA = "ARCHIVIATA",
  ELIMINATA = "ELIMINATA"
}
/*
 * Nuovi stati promo:
    PIANIFICATA ="PIANIFICATA",
    IN_LAVORAZIONE ="IN_LAVORAZIONE",
    IN_SCADENZA = "IN_SCADENZA",
    IN_ATTESA_DI_VALIDITA ="IN_ATTESA_DI_VALIDITA",
    VALIDA ="VALIDA",
    ARCHIVIATA ="ARCHIVIATA",
    IN_RITARDO = "IN_RITARDO",
    VALIDA_CON_ERRORI ="VALIDA_CON_ERRORI"

 */

export enum TIPO_KIT_DESIGN {
  MANUALE = "MANUALE",
  SEMI_AUTOMATICO = "SEMI_AUTOMATICO",
  AUTOMATICO = "AUTOMATICO"
}

export enum STATO_LAVORAZIONE_KIT_RUNTIME {
  IN_LAVORAZIONE = "IN_LAVORAZIONE",
  IN_LAVORAZIONE_CON_ERRORI = "IN_LAVORAZIONE_CON_ERRORI",
  ELIMINATO = "ELIMINATO",
  IN_REVISIONE = "IN_REVISIONE",
  PUBBLICATO = "PUBBLICATO",
}
export enum TIPO_UTENTI {
  SUPERADMIN = "Superadmin",
  AGENZIA = "Agenzia",
  GUEST = "Guest",
  PUNTOVENDITA = "PuntoVendita",
  GDO = "GDO",
  CATEGORY = "Category",
  MARKETING = "Marketing",
  IT = "IT"
}

export enum UTENTE_GENERE {
  UOMO = "UOMO",
  DONNA = "DONNA",
  ALTRO = "ALTRO",
  NON_BINARIO = "NON BINARIO",
}

export enum RUOLO_UTENTE_GDO {
  AMMINISTRATORE_DELEGATO = "AMMINISTRATORE_DELEGATO",
  DEVELOPER = "DEVELOPER",
  ADMIN = "ADMIN",
  IMPIEGATO = "IMPIEGATO",
}

//! Verranno lasciati cosi per adattarsi al codice di istanta
export const tipoUtenteReverseMapping: { [key: string]: number } = {
  [TIPO_UTENTI.SUPERADMIN]: 1,
  [TIPO_UTENTI.AGENZIA]: 2,
  [TIPO_UTENTI.GUEST]: 4,
};

export enum STATO_UTENTI {
  ATTIVO = 'ATTIVO',
  DISATTIVO = 'DISATTIVO',
  BLOCCATO = 'BLOCCATO',
  SOSPESO = 'SOSPESO',
  ELIMINATO = 'ELIMINATO',
}

export enum TIPO_CONTEXT {
  NUOVA_LAVORAZIONE = 1,
  IMPORTA_LAVORAZIONE = 2,
}

export enum TIPO_LAVORAZIONE {
  VOLANTINO = 1,
  POP = 2,
}

export enum MODALITA_TIPO_EXPORT {
  ESPORTA_TUTTO_INSIEME = "ESPORTA_TUTTO_INSIEME",
  ESPORTA_PER_PAGINA = "ESPORTA_PER_PAGINA",
}

export const modalitaTipiDiExportReverseMapping: { [key: string]: number } = {
  [MODALITA_TIPO_EXPORT.ESPORTA_TUTTO_INSIEME]: 1,
  [MODALITA_TIPO_EXPORT.ESPORTA_PER_PAGINA]: 2,
};

export enum OperationStatus {
  InAttesaDiAssegnazione = 0,
  InCoda = 1,
  ElaborazioneDati = 2,
  AttesaIO = 3,
  IO = 4,
  Cancellata = 5,
  Terminata = 6,
  TerminataConErrori = 7,
  InAttesaDiConfermaUtente = 8,
  Esaminata = 9,
  Scartata = 10,
}

export const operationStatusReverseMapping: { [key: number]: string } = {
  [OperationStatus.InAttesaDiAssegnazione]: "InAttesaDiAssegnazione",
  [OperationStatus.InCoda]: "InCoda",
  [OperationStatus.ElaborazioneDati]: "ElaborazioneDati",
  [OperationStatus.AttesaIO]: "AttesaIO",
  [OperationStatus.IO]: "IO",
  [OperationStatus.Cancellata]: "Cancellata",
  [OperationStatus.Terminata]: "Terminata",
  [OperationStatus.TerminataConErrori]: "TerminataConErrori",
  [OperationStatus.InAttesaDiConfermaUtente]: "InAttesaDiConfermaUtente",
  [OperationStatus.Esaminata]: "Esaminata",
  [OperationStatus.Scartata]: "Scartata",
};


export enum TIPO_COMANDO_CONTRATTO_TIPOGRAFIA {
  NOTIFY = "notify",
  ROLLBACK = "rollback",
  MKDIR = "mkdir",
  LOG = "log",
  DEPOSIT = "deposit",
  WARN = "warn",
}

export enum TIPO_ATTIVITA {
  CREAZIONE_UTENTE = 'CREAZIONE_UTENTE',
  ELIMINAZIONE_UTENTE = 'ELIMINAZIONE_UTENTE',
  CREAZIONE_RUNTIME_KIT_AUTOMATICO = 'CREAZIONE_RUNTIME_KIT_AUTOMATICO',
  CREAZIONE_RUNTIME_KIT_MANUALE = 'CREAZIONE_RUNTIME_KIT_MANUALE',
  UPLOAD_FILE_MANUALE = 'UPLOAD_FILE_MANUALE',
  MODIFICA_WORKSPACE_WEBPLIANT = 'MODIFICA_WORKSPACE_WEBPLIANT',
  CREAZIONE_DESIGN_KIT = 'CREAZIONE_DESIGN_KIT',
  IMPORT_TRACCIATO = 'IMPORT_TRACCIATO',
  CREAZIONE_LAVORAZIONE = 'CREAZIONE_LAVORAZIONE',
  PUBBLICAZIONE_WEBPLIANT = 'PUBBLICAZIONE_WEBPLIANT',
  RICHIESTA_WEBPLIANT = 'RICHIESTA_WEBPLIANT',
  // ordini di stampa
  CREAZIONE_ORDINE_DI_STAMPA = 'CREAZIONE_ORDINE_DI_STAMPA',
  INVIO_FILES_FTP = 'INVIO_FILES_FTP',
  INVIO_FILE_CORREGGO = 'INVIO_FILE_CORREGGO',
  PUBBLICAZIONE_FILE_CORREGGO = 'PUBBLICAZIONE_FILE_CORREGGO',
}

/**
 * Categorie per raggruppare le attività nel pannello notifiche
 */
export enum CATEGORIA_ATTIVITA {
  ACCOUNT = 'ACCOUNT',           // Gestione utenti
  PRODUZIONE = 'PRODUZIONE',     // Kit, file, lavorazioni
  PUBBLICAZIONE = 'PUBBLICAZIONE', // WebPliant
  STAMPA = 'STAMPA',             // Ordini di stampa, FTP
  INTEGRAZIONI = 'INTEGRAZIONI', // Correggo, servizi esterni
}

/**
 * Priorità delle notifiche per gestire visualizzazione e retention
 */
export enum PRIORITA_ATTIVITA {
  ALTA = 'ALTA',     // Toast + Badge + Sound (opt) - Retention 90 giorni
  MEDIA = 'MEDIA',   // Toast + Badge - Retention 30 giorni
  BASSA = 'BASSA',   // Solo panel, no toast - Retention 7 giorni
}


export enum TIPI_CANALI_INTERAZIONE {
  WHATSAPP = "WHATSAPP",
  EMAIL = "EMAIL",
  SMS = "SMS",
  TELEGRAM = "TELEGRAM",
  LINKEDIN = "LINKEDIN",
  FACEBOOK = "FACEBOOK",
  GOOGLE = "GOOGLE",
  INSTAGRAM = "INSTAGRAM",
  APPLE = "APPLE",
}
export enum STATO_CANALI_INTERAZIONE {
  ATTIVO = "ATTIVO",
  DISATTIVO = "DISATTIVO",
  SOSPESO = "SOSPESO",
  ELIMINATO = "ELIMINATO",
}

export enum STATO_ORDINI_STAMPA {
  ERRORE = "ERRORE",
  IN_REVISIONE = "IN_REVISIONE",
  REVISIONATO = "REVISIONATO",
  FINITO = "FINITO",
}

export enum ItemDisposition {
  grid = 'grid',
  list = 'list',
}

export const itemDispositionMap = {
  [ItemDisposition.grid]: 0,
  [ItemDisposition.list]: 1,
};


export enum TIPO_PAGINA {
  HOMEPAGE = "HOMEPAGE",
  CATEGORIA = "CATEGORIA",
  PRODOTTO = "PRODOTTO",
  RICETTA = "RICETTA",
  RICETTA_AI = "RICETTA_AI",
  PROMOZIONE = "PROMOZIONE",
  WISHLIST = "WISHLIST",
}

export enum InteractionType {
  WORKSPACE = "WORKSPACE",
  PAGES = "PAGES",
  SECTION = "SECTION",
  SINGLE_SERVICE = "SINGLE_SERVICE",
}

/**
 * Enumeratore con i possibili campi su cui puoi fare policy
 */
export enum FieldType {
  VUOTO = "",
  REFERENZE = "REFERENZE",
  DATA_SCADENZA = "DATA_SCADENZA",
  RICORRENZA = "RICORRENZA",
  AREA = "AREA",
  CANALE = "CANALE",
  PUNTO_VENDITA = "PUNTO_VENDITA",
  CONTESTO_KIT = "CONTESTO_KIT",
}
// Aggiungi alla fine del file esistente, dopo gli altri enum

export enum EVENTI_WEBHOOK {
  // Eventi Utente
  UTENTE_CREATO = 'UTENTE_CREATO',
  UTENTE_AGGIORNATO = 'UTENTE_AGGIORNATO',
  UTENTE_AUTENTICATO = 'UTENTE_AUTENTICATO',
  UTENTE_DISCONNESSO = 'UTENTE_DISCONNESSO',

  // Eventi Promo
  PROMO_CREATA = 'PROMO_CREATA',
  PROMO_AGGIORNATA = 'PROMO_AGGIORNATA',
  PROMO_AVVIATA = 'PROMO_AVVIATA',
  PROMO_COMPLETATA = 'PROMO_COMPLETATA',
  PROMO_ELIMINATA = 'PROMO_ELIMINATA',

  // Eventi Kit
  KIT_CREATO = 'KIT_CREATO',
  KIT_STATO_CAMBIATO = 'KIT_STATO_CAMBIATO',
  KIT_FILE_CARICATI = 'KIT_FILE_CARICATI',
  KIT_FILE_CANCELLATI = 'KIT_FILE_CANCELLATI',
  KIT_PUBBLICATO = 'KIT_PUBBLICATO',
  KIT_IN_REVISIONE = 'KIT_IN_REVISIONE',
  KIT_MATERIALE_ARRIVATO = 'KIT_MATERIALE_ARRIVATO',
  // Eventi File
  FILE_CARICATO = 'FILE_CARICATO',
  FILE_ELIMINATO = 'FILE_ELIMINATO',
  FILE_ELABORATO = 'FILE_ELABORATO',

  // Eventi Ordini
  ORDINE_CREATO = 'ORDINE_CREATO',
  ORDINE_AGGIORNATO = 'ORDINE_AGGIORNATO',
  ORDINE_COMPLETATO = 'ORDINE_COMPLETATO',
  ORDINE_ANNULLATO = 'ORDINE_ANNULLATO',

  // Eventi WebPliant
  WEBPLIANT_CREATO = 'WEBPLIANT_CREATO',
  WEBPLIANT_PUBBLICATO = 'WEBPLIANT_PUBBLICATO',
  WORKSPACE_MODIFICATO = 'WORKSPACE_MODIFICATO',

  // Eventi Sistema
  SISTEMA_BACKUP_COMPLETATO = 'SISTEMA_BACKUP_COMPLETATO',
  SISTEMA_MANUTENZIONE_INIZIATA = 'SISTEMA_MANUTENZIONE_INIZIATA',
  SISTEMA_MANUTENZIONE_COMPLETATA = 'SISTEMA_MANUTENZIONE_COMPLETATA',
  SISTEMA_ERRORE = 'SISTEMA_ERRORE'

}

export enum STATO_WEBHOOK {
  ATTIVO = 'ATTIVO',
  DISATTIVO = 'DISATTIVO',
  ERRORE = 'ERRORE',
  SOSPESO = 'SOSPESO',
  ELIMINATO = 'ELIMINATO'
}

export enum STATO_TENTATIVO_WEBHOOK {
  IN_ATTESA = 'IN_ATTESA',
  SUCCESSO = 'SUCCESSO',
  FALLITO = 'FALLITO',
  RETRY = 'RETRY',
  TIMEOUT = 'TIMEOUT'
}



export enum STATO_LOG_FILE {
  IN_ATTESA = "IN_ATTESA",
  IN_REVISIONE = "IN_REVISIONE",
  ACCETTATO = "ACCETTATO",
  ERRORE = "ERRORE",
  PUBBLICATO = "PUBBLICATO",
  IN_ATTESA_DI_CORREGGO = "IN_ATTESA_DI_CORREGGO",
  CORREGGO_PUBBLICATO = "CORREGGO_PUBBLICATO",
  CORREGGO_ERRORE = "CORREGGO_ERRORE",
}

export enum PROVIDER_WHATSAPP {
  META = "META",
}
export enum STATO_GDO_WHATSAPP_NUMBER {
  PENDING = "PENDING",
  VERIFIED = "VERIFIED",
  PAUSED = "PAUSED"
}
export enum STATO_GDO_WHATSAPP_TEMPLATE {
  APPROVED = 'APPROVED',
  PENDING = 'PENDING',
  REJECTED = 'REJECTED',
  PAUSED = 'PAUSED',
  DISABLED = 'DISABLED',
  DELETED = 'DELETED',
  ARCHIVED = 'ARCHIVED',
  PENDING_DELETION = 'PENDING_DELETION',
  IN_APPEAL = 'IN_APPEAL',
  LIMIT_EXCEEDED = 'LIMIT_EXCEEDED',
  //NOTE: STATI PERSONALIZZATI
  CREATED_BUT_NOT_SYNCED = 'CREATED_BUT_NOT_SYNCED',
}
export enum CATEGORIA_TEMPLATE_WHATSAPP {
  MARKETING = 'MARKETING',
  UTILITY = 'UTILITY',
  AUTHENTICATION = 'AUTHENTICATION',
  TRANSACTIONAL = 'TRANSACTIONAL',
  SERVICE = 'SERVICE',
}


export enum GDOWhatsappQueueJobStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
}

export enum CATEGORIA_PERMESSO {
  PAGINA = 'PAGINA',
  AZIONE = 'AZIONE',
}

export enum TIPO_MENU_ITEM {
  SEPARATOR = 'separator',
  ITEM = 'item',
}

export enum EXPORT_DI_SISTEMA {
  CORREGGO = "CORREGGO",
  VOL = "VOL"
}

export enum AUTH_PROVIDER_TIPO {
  INTERNAL = 'internal',
  OIDC = 'oidc',
  SAML = 'saml',
  CUSTOM = 'custom',
}

export enum HUB_SERVICE_URL_TIPO {
  INTERNAL = 'internal',
  EXTERNAL = 'external',
}

export enum HUB_NEWS_TIPO {
  INFO = 'info',
  WARNING = 'warning',
  SUCCESS = 'success',
  UPDATE = 'update',
}
