-- Type: STATO_COMBINAZIONE_CANALE_AREA

-- Rimozione tipo esistente (ATTENZIONE: Verificare dipendenze prima di eseguire)
-- DROP TYPE IF EXISTS public."STATO_COMBINAZIONE_CANALE_AREA" CASCADE;

CREATE TYPE public."STATO_COMBINAZIONE_CANALE_AREA" AS ENUM
    ('ATTIVO', 'DISATTIVO');

ALTER TYPE public."STATO_COMBINAZIONE_CANALE_AREA"
    OWNER TO postgres;
