-- Type: TIPO_ATTIVITA

-- Rimozione tipo esistente (ATTENZIONE: Verificare dipendenze prima di eseguire)
-- DROP TYPE IF EXISTS public."TIPO_ATTIVITA" CASCADE;

CREATE TYPE public."TIPO_ATTIVITA" AS ENUM
    ('CREAZIONE_UTENTE', 'ELIMINAZIONE_UTENTE', 'CREAZIONE_RUNTIME_KIT_AUTOMATICO', 'CREAZIONE_RUNTIME_KIT_MANUALE', 'UPLOAD_FILE_MANUALE', 'MODIFICA_WORKSPACE_WEBPLIANT', 'CREAZIONE_DESIGN_KIT', 'IMPORT_TRACCIATO', 'CREAZIONE_LAVORAZIONE', 'PUBBLICAZIONE_WEBPLIANT', 'RICHIESTA_WEBPLIANT', 'CREAZIONE_ORDINE_DI_STAMPA', 'INVIO_FILES_FTP', 'INVIO_FILE_CORREGGO', 'PUBBLICAZIONE_FILE_CORREGGO');

ALTER TYPE public."TIPO_ATTIVITA"
    OWNER TO postgres;
